// microKORG S patch library — 256 patches
// Bank A: Basses  Bank B: Keys  Bank C: Pads  Bank D: FX
// VP Src 6=Mod wheel routed on every patch (Src 7=PitchBend)
// NO global FX by default - clean patches, enable FX manually on hardware

const MC  = (n) => ({ vp2Src:6, vp2Dst:4, vp2Int:n });  // Mod→Cutoff
const MP  = (n) => ({ vp2Src:6, vp2Dst:0, vp2Int:n });  // Mod→Pitch (only whistles)
const MO2 = (n) => ({ vp2Src:6, vp2Dst:1, vp2Int:n });  // Mod→OSC2Pitch
const MC1 = (n) => ({ vp2Src:6, vp2Dst:2, vp2Int:n });  // Mod→Ctrl1
const ML  = (n) => ({ vp2Src:6, vp2Dst:7, vp2Int:n });  // Mod→LFO2Freq
const MA  = (n) => ({ vp2Src:6, vp2Dst:5, vp2Int:n });  // Mod→AMP

const patches = [
  {
    "name": "Deep Sine",
    "osc1Wave": 3,
    "osc1Level": 115,
    "filterCutoff": 47,
    "filterResonance": 8,
    "ampAttack": 0,
    "ampSustain": 100,
    "ampRelease": 40,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Warm Sub",
    "osc1Wave": 0,
    "osc1Level": 110,
    "filterCutoff": 50,
    "filterResonance": 20,
    "ampAttack": 0,
    "ampSustain": 100,
    "ampRelease": 40,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Round Sub",
    "osc1Wave": 2,
    "osc1Level": 110,
    "filterCutoff": 43,
    "filterResonance": 14,
    "ampAttack": 0,
    "ampSustain": 100,
    "ampRelease": 40,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Fat Sub",
    "osc1Wave": 3,
    "osc2Wave": 0,
    "osc1Level": 110,
    "osc2Level": 45,
    "filterCutoff": 45,
    "filterResonance": 18,
    "ampAttack": 0,
    "ampSustain": 100,
    "ampRelease": 40,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "G-Funk Sub",
    "osc1Wave": 3,
    "osc1Level": 112,
    "filterCutoff": 53,
    "filterResonance": 14,
    "ampAttack": 0,
    "ampSustain": 100,
    "ampRelease": 40,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "808 Boom",
    "osc1Wave": 3,
    "osc1Level": 115,
    "filterCutoff": 40,
    "filterResonance": 10,
    "ampAttack": 0,
    "ampDecay": 100,
    "ampSustain": 45,
    "ampRelease": 40,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Cloudy Sub",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 110,
    "osc2Level": 82,
    "filterCutoff": 50,
    "filterResonance": 18,
    "ampAttack": 0,
    "ampSustain": 100,
    "ampRelease": 40,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Sub+Air",
    "osc1Wave": 3,
    "osc1Level": 110,
    "noiseLevel": 20,
    "filterCutoff": 47,
    "filterResonance": 12,
    "ampAttack": 0,
    "ampSustain": 100,
    "ampRelease": 40,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Clean 303",
    "osc1Wave": 0,
    "osc1Level": 110,
    "filterCutoff": 48,
    "filterResonance": 92,
    "filterEgInt": 52,
    "filterAttack": 0,
    "filterDecay": 25,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampSustain": 90,
    "ampRelease": 22,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 1,
    "vp2Int": 30
  },
  {
    "name": "Creamy Acid",
    "osc1Wave": 2,
    "osc1Level": 108,
    "filterCutoff": 50,
    "filterResonance": 95,
    "filterEgInt": 48,
    "filterAttack": 0,
    "filterDecay": 25,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampSustain": 90,
    "ampRelease": 25,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 1,
    "vp2Int": 30
  },
  {
    "name": "Morning Acid",
    "osc1Wave": 0,
    "osc1Level": 108,
    "filterCutoff": 52,
    "filterResonance": 80,
    "filterEgInt": 45,
    "filterAttack": 0,
    "filterDecay": 25,
    "filterSustain": 10,
    "ampAttack": 0,
    "ampSustain": 90,
    "ampRelease": 25,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 1,
    "vp2Int": 30
  },
  {
    "name": "Squelch",
    "osc1Wave": 0,
    "osc1Level": 112,
    "filterCutoff": 42,
    "filterResonance": 112,
    "filterEgInt": 58,
    "filterAttack": 0,
    "filterDecay": 22,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampSustain": 85,
    "ampRelease": 20,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 1,
    "vp2Int": 30
  },
  {
    "name": "Slow Acid",
    "osc1Wave": 0,
    "osc1Level": 108,
    "filterCutoff": 45,
    "filterResonance": 88,
    "filterEgInt": 50,
    "filterAttack": 0,
    "filterDecay": 25,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampSustain": 90,
    "ampRelease": 25,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 1,
    "vp2Int": 30
  },
  {
    "name": "Bubble Acid",
    "osc1Wave": 0,
    "osc1Level": 108,
    "filterCutoff": 48,
    "filterResonance": 95,
    "filterEgInt": 50,
    "filterDecay": 25,
    "filterSustain": 0,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 48,
    "lfo1Wave": 2,
    "lfo1Rate": 68,
    "ampAttack": 0,
    "ampSustain": 90,
    "ampRelease": 25,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 1,
    "vp2Int": 30,
    "filterAttack": 0
  },
  {
    "name": "Sine Acid",
    "osc1Wave": 3,
    "osc1Level": 110,
    "filterCutoff": 45,
    "filterResonance": 100,
    "filterEgInt": 50,
    "filterAttack": 0,
    "filterDecay": 25,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampSustain": 90,
    "ampRelease": 22,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 1,
    "vp2Int": 30
  },
  {
    "name": "Square Acid",
    "osc1Wave": 1,
    "osc1Level": 108,
    "filterCutoff": 42,
    "filterResonance": 98,
    "filterEgInt": 52,
    "filterAttack": 0,
    "filterDecay": 25,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampSustain": 88,
    "ampRelease": 22,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 1,
    "vp2Int": 30
  },
  {
    "name": "Funk Wah",
    "osc1Wave": 0,
    "osc1Level": 110,
    "filterCutoff": 38,
    "filterResonance": 82,
    "filterEgInt": 58,
    "filterAttack": 0,
    "filterDecay": 48,
    "filterSustain": 0,
    "ampAttack": 2,
    "ampSustain": 88,
    "ampRelease": 40,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 42
  },
  {
    "name": "Parliament",
    "osc1Wave": 0,
    "osc1Level": 110,
    "filterCutoff": 35,
    "filterResonance": 78,
    "filterEgInt": 62,
    "filterAttack": 0,
    "filterDecay": 45,
    "filterSustain": 0,
    "ampAttack": 2,
    "ampSustain": 88,
    "ampRelease": 42,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 42
  },
  {
    "name": "Bounce",
    "osc1Wave": 0,
    "osc1Level": 110,
    "filterCutoff": 42,
    "filterResonance": 72,
    "filterEgInt": 55,
    "filterAttack": 0,
    "filterDecay": 35,
    "filterSustain": 18,
    "ampAttack": 1,
    "ampDecay": 40,
    "ampSustain": 72,
    "ampRelease": 30,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 42
  },
  {
    "name": "Clavey",
    "osc1Wave": 1,
    "osc1Level": 110,
    "filterCutoff": 78,
    "filterResonance": 62,
    "filterEgInt": 48,
    "filterAttack": 0,
    "filterDecay": 22,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 35,
    "ampSustain": 40,
    "ampRelease": 22,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 42
  },
  {
    "name": "Sticky",
    "osc1Wave": 0,
    "osc1Level": 108,
    "filterCutoff": 40,
    "filterResonance": 70,
    "filterEgInt": 52,
    "filterAttack": 2,
    "filterDecay": 60,
    "filterSustain": 20,
    "ampAttack": 2,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 42
  },
  {
    "name": "Moog Wah",
    "osc1Wave": 0,
    "osc1Level": 110,
    "filterCutoff": 45,
    "filterResonance": 68,
    "filterEgInt": 55,
    "filterAttack": 0,
    "filterDecay": 42,
    "filterSustain": 10,
    "ampAttack": 2,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 42
  },
  {
    "name": "Pluck Funk",
    "osc1Wave": 0,
    "osc1Level": 112,
    "filterCutoff": 82,
    "filterResonance": 58,
    "filterEgInt": 45,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 30,
    "ampSustain": 0,
    "ampRelease": 18,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 42
  },
  {
    "name": "Snap Bass",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 88,
    "filterResonance": 45,
    "filterEgInt": 38,
    "filterAttack": 0,
    "filterDecay": 15,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 18,
    "ampSustain": 0,
    "ampRelease": 12,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 42
  },
  {
    "name": "Pure Sub",
    "osc1Wave": 3,
    "osc1Level": 120,
    "filterCutoff": 35,
    "filterResonance": 0,
    "ampAttack": 0,
    "ampSustain": 100,
    "ampRelease": 35,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 35
  },
  {
    "name": "Deep Sub",
    "osc1Wave": 3,
    "osc1Level": 115,
    "filterCutoff": 32,
    "filterResonance": 5,
    "ampAttack": 0,
    "ampSustain": 100,
    "ampRelease": 40,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 38
  },
  {
    "name": "Clean Saw",
    "osc1Wave": 0,
    "osc1Level": 112,
    "filterCutoff": 45,
    "filterResonance": 0,
    "ampAttack": 0,
    "ampSustain": 100,
    "ampRelease": 35,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 32
  },
  {
    "name": "Tight Sine",
    "osc1Wave": 3,
    "osc1Level": 118,
    "filterCutoff": 50,
    "filterResonance": 8,
    "ampAttack": 0,
    "ampSustain": 100,
    "ampRelease": 30,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Bright Sub",
    "osc1Wave": 2,
    "osc1Level": 115,
    "filterCutoff": 55,
    "filterResonance": 12,
    "ampAttack": 1,
    "ampSustain": 100,
    "ampRelease": 35,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 38
  },
  {
    "name": "Mid Sub",
    "osc1Wave": 0,
    "osc1Level": 110,
    "filterCutoff": 60,
    "filterResonance": 10,
    "ampAttack": 2,
    "ampSustain": 95,
    "ampRelease": 40,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 40
  },
  {
    "name": "Tight Tri",
    "osc1Wave": 2,
    "osc1Level": 112,
    "filterCutoff": 48,
    "filterResonance": 6,
    "ampAttack": 0,
    "ampSustain": 100,
    "ampRelease": 35,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Rolling Sub",
    "osc1Wave": 3,
    "osc1Level": 108,
    "filterCutoff": 58,
    "filterResonance": 18,
    "ampAttack": 3,
    "ampSustain": 100,
    "ampRelease": 50,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 45
  },
  {
    "name": "Bass Pluck",
    "osc1Wave": 0,
    "osc1Level": 112,
    "filterCutoff": 88,
    "filterResonance": 58,
    "filterEgInt": 48,
    "filterAttack": 0,
    "filterDecay": 22,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 30,
    "ampSustain": 0,
    "ampRelease": 20,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 5,
    "vp2Int": 28
  },
  {
    "name": "Techno Pluck",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 95,
    "filterResonance": 52,
    "filterEgInt": 42,
    "filterAttack": 0,
    "filterDecay": 18,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 22,
    "ampSustain": 0,
    "ampRelease": 15,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 5,
    "vp2Int": 28
  },
  {
    "name": "Deep Pluck",
    "osc1Wave": 0,
    "osc1Level": 110,
    "filterCutoff": 58,
    "filterResonance": 72,
    "filterEgInt": 52,
    "filterAttack": 0,
    "filterDecay": 30,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 35,
    "ampSustain": 0,
    "ampRelease": 22,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 5,
    "vp2Int": 28
  },
  {
    "name": "Blip Bass",
    "osc1Wave": 3,
    "osc1Level": 112,
    "filterCutoff": 75,
    "filterResonance": 42,
    "filterEgInt": 40,
    "filterAttack": 0,
    "filterDecay": 15,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 15,
    "ampSustain": 0,
    "ampRelease": 12,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 5,
    "vp2Int": 28
  },
  {
    "name": "Stab Low",
    "osc1Wave": 0,
    "osc2Wave": 1,
    "osc1Level": 105,
    "osc2Level": 50,
    "filterCutoff": 85,
    "filterResonance": 48,
    "filterEgInt": 38,
    "filterDecay": 18,
    "ampAttack": 0,
    "ampDecay": 22,
    "ampSustain": 0,
    "ampRelease": 15,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 5,
    "vp2Int": 28
  },
  {
    "name": "Attack Saw",
    "osc1Wave": 0,
    "osc1Level": 112,
    "filterCutoff": 82,
    "filterResonance": 52,
    "filterEgInt": 45,
    "filterAttack": 0,
    "filterDecay": 25,
    "filterSustain": 20,
    "ampAttack": 1,
    "ampDecay": 35,
    "ampSustain": 60,
    "ampRelease": 25,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 5,
    "vp2Int": 28
  },
  {
    "name": "Piano Bass",
    "osc1Wave": 5,
    "osc1Level": 108,
    "filterCutoff": 90,
    "filterResonance": 25,
    "ampAttack": 0,
    "ampDecay": 50,
    "ampSustain": 30,
    "ampRelease": 25,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 5,
    "vp2Int": 28
  },
  {
    "name": "Marimba Low",
    "osc1Wave": 2,
    "osc1Level": 105,
    "filterCutoff": 92,
    "filterResonance": 38,
    "filterEgInt": 32,
    "filterDecay": 20,
    "ampAttack": 0,
    "ampDecay": 30,
    "ampSustain": 0,
    "ampRelease": 25,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 5,
    "vp2Int": 28
  },
  {
    "name": "Wobble",
    "osc1Wave": 0,
    "osc1Level": 110,
    "filterCutoff": 60,
    "filterResonance": 78,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 42,
    "lfo1Wave": 2,
    "lfo1Rate": 75,
    "ampAttack": 2,
    "ampSustain": 100,
    "ampRelease": 40,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 40
  },
  {
    "name": "Bubble Bass",
    "osc1Wave": 0,
    "osc1Level": 110,
    "filterCutoff": 52,
    "filterResonance": 90,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 52,
    "lfo1Wave": 2,
    "lfo1Rate": 70,
    "ampAttack": 1,
    "ampSustain": 100,
    "ampRelease": 35,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 40
  },
  {
    "name": "Morphing",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 100,
    "osc2Level": 70,
    "filterCutoff": 55,
    "filterResonance": 52,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 32,
    "lfo1Wave": 2,
    "lfo1Rate": 60,
    "ampAttack": 2,
    "ampSustain": 100,
    "ampRelease": 50,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 40
  },
  {
    "name": "Tremolo Sub",
    "osc1Wave": 3,
    "osc1Level": 112,
    "filterCutoff": 55,
    "filterResonance": 14,
    "vp1Src": 2,
    "vp1Dst": 5,
    "vp1Int": 42,
    "lfo1Wave": 1,
    "lfo1Rate": 60,
    "ampAttack": 2,
    "ampSustain": 100,
    "ampRelease": 50,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 40
  },
  {
    "name": "Ripple",
    "osc1Wave": 0,
    "osc1Level": 108,
    "filterCutoff": 62,
    "filterResonance": 48,
    "vp1Src": 2,
    "vp1Dst": 0,
    "vp1Int": 10,
    "lfo1Wave": 2,
    "lfo1Rate": 70,
    "ampAttack": 2,
    "ampSustain": 100,
    "ampRelease": 50,
    "vibratoIntensity": 40,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 40
  },
  {
    "name": "Pumping",
    "osc1Wave": 0,
    "osc1Level": 112,
    "filterCutoff": 68,
    "filterResonance": 58,
    "vp1Src": 2,
    "vp1Dst": 5,
    "vp1Int": 52,
    "lfo1Wave": 1,
    "lfo1Rate": 62,
    "ampAttack": 2,
    "ampSustain": 100,
    "ampRelease": 30,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 40
  },
  {
    "name": "Pulsing",
    "osc1Wave": 0,
    "osc1Level": 110,
    "filterCutoff": 50,
    "filterResonance": 82,
    "filterEgInt": 48,
    "filterDecay": 35,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 38,
    "lfo1Wave": 2,
    "lfo1Rate": 75,
    "ampAttack": 1,
    "ampSustain": 100,
    "ampRelease": 40,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 40
  },
  {
    "name": "Flow",
    "osc1Wave": 2,
    "osc2Wave": 0,
    "osc1Level": 95,
    "osc2Level": 80,
    "filterCutoff": 58,
    "filterResonance": 38,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 30,
    "lfo1Wave": 2,
    "lfo1Rate": 60,
    "ampAttack": 2,
    "ampSustain": 100,
    "ampRelease": 55,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 40
  },
  {
    "name": "Goa Acid",
    "osc1Wave": 0,
    "osc1Level": 112,
    "filterCutoff": 50,
    "filterResonance": 100,
    "filterEgInt": 52,
    "filterAttack": 0,
    "filterDecay": 25,
    "filterSustain": 0,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 42,
    "lfo1Wave": 2,
    "lfo1Rate": 68,
    "ampAttack": 0,
    "ampSustain": 100,
    "ampRelease": 30,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 38
  },
  {
    "name": "Forest Bass",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 105,
    "osc2Level": 65,
    "filterCutoff": 48,
    "filterResonance": 82,
    "filterEgInt": 48,
    "filterDecay": 30,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 40,
    "lfo1Wave": 2,
    "lfo1Rate": 55,
    "ampAttack": 0,
    "ampSustain": 100,
    "ampRelease": 32,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 38
  },
  {
    "name": "Full On",
    "osc1Wave": 0,
    "osc1Level": 112,
    "filterCutoff": 52,
    "filterResonance": 92,
    "filterEgInt": 55,
    "filterAttack": 0,
    "filterDecay": 26,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampSustain": 100,
    "ampRelease": 28,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 38
  },
  {
    "name": "Morning Psy",
    "osc1Wave": 0,
    "osc1Level": 108,
    "filterCutoff": 62,
    "filterResonance": 85,
    "filterEgInt": 48,
    "filterDecay": 28,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 38,
    "lfo1Wave": 2,
    "lfo1Rate": 70,
    "ampAttack": 0,
    "ampSustain": 100,
    "ampRelease": 30,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 38
  },
  {
    "name": "Alien Groove",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc2Mod": 1,
    "osc1Level": 100,
    "osc2Level": 72,
    "filterCutoff": 52,
    "filterResonance": 85,
    "filterEgInt": 48,
    "filterDecay": 30,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 42,
    "lfo1Wave": 2,
    "lfo1Rate": 60,
    "ampAttack": 0,
    "ampSustain": 100,
    "ampRelease": 32,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 38
  },
  {
    "name": "Spiral Bass",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 105,
    "osc2Level": 80,
    "filterCutoff": 50,
    "filterResonance": 95,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 50,
    "lfo1Wave": 2,
    "lfo1Rate": 65,
    "ampAttack": 0,
    "ampSustain": 100,
    "ampRelease": 35,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 38
  },
  {
    "name": "Psyche Sub",
    "osc1Wave": 3,
    "osc2Wave": 0,
    "osc1Level": 112,
    "osc2Level": 48,
    "filterCutoff": 50,
    "filterResonance": 20,
    "ampAttack": 1,
    "ampSustain": 100,
    "ampRelease": 55,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 38
  },
  {
    "name": "Twisting",
    "osc1Wave": 1,
    "osc2Wave": 2,
    "osc1Level": 100,
    "osc2Level": 78,
    "filterCutoff": 50,
    "filterResonance": 92,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 48,
    "lfo1Wave": 2,
    "lfo1Rate": 60,
    "ampAttack": 0,
    "ampSustain": 100,
    "ampRelease": 35,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 38
  },
  {
    "name": "Compton",
    "osc1Wave": 3,
    "osc2Wave": 2,
    "osc1Level": 112,
    "osc2Level": 40,
    "filterCutoff": 50,
    "filterResonance": 15,
    "ampAttack": 2,
    "ampSustain": 100,
    "ampRelease": 60,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 1,
    "vp2Int": 32
  },
  {
    "name": "Slap Synth",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 90,
    "filterResonance": 45,
    "filterEgInt": 40,
    "filterDecay": 18,
    "ampAttack": 0,
    "ampDecay": 22,
    "ampSustain": 40,
    "ampRelease": 18,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 1,
    "vp2Int": 32
  },
  {
    "name": "Rubber Band",
    "osc1Wave": 0,
    "osc1Level": 108,
    "filterCutoff": 75,
    "filterResonance": 55,
    "filterEgInt": 48,
    "filterDecay": 40,
    "ampAttack": 2,
    "ampSustain": 100,
    "ampRelease": 50,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 1,
    "vp2Int": 32
  },
  {
    "name": "Detroit Deep",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 100,
    "osc2Level": 52,
    "filterCutoff": 55,
    "filterResonance": 45,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 30,
    "lfo1Wave": 2,
    "lfo1Rate": 12,
    "ampAttack": 2,
    "ampSustain": 100,
    "ampRelease": 60,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 1,
    "vp2Int": 32
  },
  {
    "name": "Dub Bass",
    "osc1Wave": 0,
    "osc1Level": 105,
    "filterCutoff": 62,
    "filterResonance": 30,
    "ampAttack": 2,
    "ampDecay": 80,
    "ampSustain": 62,
    "ampRelease": 60,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 1,
    "vp2Int": 32
  },
  {
    "name": "UK Garage",
    "osc1Wave": 0,
    "osc1Level": 112,
    "filterCutoff": 76,
    "filterResonance": 60,
    "filterEgInt": 46,
    "filterDecay": 26,
    "ampAttack": 0,
    "ampDecay": 30,
    "ampSustain": 60,
    "ampRelease": 22,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 1,
    "vp2Int": 32
  },
  {
    "name": "Deep House",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 105,
    "osc2Level": 50,
    "filterCutoff": 63,
    "filterResonance": 35,
    "filterEgInt": 40,
    "filterDecay": 42,
    "ampAttack": 2,
    "ampSustain": 100,
    "ampRelease": 55,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 1,
    "vp2Int": 32
  },
  {
    "name": "House Sub",
    "osc1Wave": 3,
    "osc2Wave": 0,
    "osc1Level": 110,
    "osc2Level": 38,
    "filterCutoff": 58,
    "filterResonance": 20,
    "ampAttack": 2,
    "ampSustain": 100,
    "ampRelease": 58,
    "transpose": -12,
    "vp2Src": 6,
    "vp2Dst": 1,
    "vp2Int": 32
  },
  {
    "name": "Crystal Plk",
    "osc1Wave": 3,
    "osc1Level": 108,
    "filterCutoff": 100,
    "filterResonance": 38,
    "filterEgInt": 42,
    "filterDecay": 25,
    "ampAttack": 0,
    "ampDecay": 40,
    "ampSustain": 0,
    "ampRelease": 28,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Bright Pluck",
    "osc1Wave": 0,
    "osc1Level": 110,
    "filterCutoff": 105,
    "filterResonance": 48,
    "filterEgInt": 45,
    "filterDecay": 22,
    "ampAttack": 0,
    "ampDecay": 32,
    "ampSustain": 0,
    "ampRelease": 22,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Synth Pluck",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 100,
    "osc2Level": 52,
    "filterCutoff": 98,
    "filterResonance": 42,
    "filterEgInt": 40,
    "filterDecay": 24,
    "ampAttack": 0,
    "ampDecay": 35,
    "ampSustain": 0,
    "ampRelease": 25,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Bell Key",
    "osc1Wave": 3,
    "osc2Wave": 0,
    "osc2Mod": 1,
    "osc1Level": 100,
    "osc2Level": 60,
    "filterCutoff": 100,
    "filterResonance": 30,
    "ampAttack": 0,
    "ampDecay": 55,
    "ampSustain": 0,
    "ampRelease": 40,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 20
  },
  {
    "name": "Funky Clav",
    "osc1Wave": 1,
    "osc1Level": 110,
    "filterCutoff": 108,
    "filterResonance": 55,
    "filterEgInt": 45,
    "filterDecay": 18,
    "ampAttack": 0,
    "ampDecay": 28,
    "ampSustain": 40,
    "ampRelease": 20,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Harpsichord",
    "osc1Wave": 1,
    "osc1Level": 110,
    "filterCutoff": 112,
    "filterResonance": 24,
    "filterEgInt": 35,
    "filterDecay": 15,
    "ampAttack": 0,
    "ampDecay": 28,
    "ampSustain": 0,
    "ampRelease": 18,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 20
  },
  {
    "name": "Metal Pluck",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc2Mod": 1,
    "osc1Level": 100,
    "osc2Level": 82,
    "filterCutoff": 95,
    "filterResonance": 45,
    "filterEgInt": 38,
    "filterDecay": 22,
    "ampAttack": 0,
    "ampDecay": 35,
    "ampSustain": 0,
    "ampRelease": 25,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Glass Key",
    "osc1Wave": 2,
    "osc1Level": 105,
    "filterCutoff": 110,
    "filterResonance": 50,
    "filterEgInt": 38,
    "filterDecay": 28,
    "ampAttack": 0,
    "ampDecay": 45,
    "ampSustain": 0,
    "ampRelease": 30,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 20
  },
  {
    "name": "Rhodes Warm",
    "osc1Wave": 5,
    "osc1Level": 105,
    "filterCutoff": 88,
    "filterResonance": 20,
    "ampAttack": 5,
    "ampDecay": 52,
    "ampSustain": 72,
    "ampRelease": 50,
    "vp1Src": 4,
    "vp1Dst": 5,
    "vp1Int": 35,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "E.Piano",
    "osc1Wave": 5,
    "osc1Level": 105,
    "filterCutoff": 92,
    "filterResonance": 22,
    "ampAttack": 4,
    "ampDecay": 48,
    "ampSustain": 75,
    "ampRelease": 46,
    "vp1Src": 4,
    "vp1Dst": 5,
    "vp1Int": 35,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Vintage Keys",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 95,
    "osc2Level": 82,
    "filterCutoff": 85,
    "filterResonance": 28,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 15,
    "lfo1Wave": 2,
    "lfo1Rate": 28,
    "ampAttack": 7,
    "ampDecay": 46,
    "ampSustain": 80,
    "ampRelease": 54,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Mellow Keys",
    "osc1Wave": 2,
    "osc1Level": 105,
    "filterCutoff": 80,
    "filterResonance": 18,
    "ampAttack": 10,
    "ampDecay": 50,
    "ampSustain": 82,
    "ampRelease": 60,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 22
  },
  {
    "name": "Jazzy Keys",
    "osc1Wave": 5,
    "osc1Level": 102,
    "filterCutoff": 85,
    "filterResonance": 25,
    "filterEgInt": 22,
    "filterDecay": 35,
    "ampAttack": 6,
    "ampDecay": 46,
    "ampSustain": 78,
    "ampRelease": 52,
    "vp1Src": 4,
    "vp1Dst": 5,
    "vp1Int": 30,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Rhodes Dark",
    "osc1Wave": 5,
    "osc1Level": 100,
    "filterCutoff": 76,
    "filterResonance": 22,
    "ampAttack": 6,
    "ampDecay": 56,
    "ampSustain": 70,
    "ampRelease": 54,
    "vp1Src": 4,
    "vp1Dst": 5,
    "vp1Int": 35,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Warm Bell",
    "osc1Wave": 3,
    "osc1Level": 105,
    "filterCutoff": 92,
    "filterResonance": 24,
    "ampAttack": 3,
    "ampDecay": 62,
    "ampSustain": 0,
    "ampRelease": 58,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 20
  },
  {
    "name": "Soft Keys",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 95,
    "osc2Level": 78,
    "filterCutoff": 78,
    "filterResonance": 20,
    "ampAttack": 14,
    "ampDecay": 50,
    "ampSustain": 82,
    "ampRelease": 60,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Bell Pure",
    "osc1Wave": 3,
    "osc2Wave": 0,
    "osc2Mod": 1,
    "osc1Level": 100,
    "osc2Level": 58,
    "filterCutoff": 102,
    "filterResonance": 28,
    "ampAttack": 0,
    "ampDecay": 68,
    "ampSustain": 0,
    "ampRelease": 58,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 20
  },
  {
    "name": "Marimba",
    "osc1Wave": 2,
    "osc1Level": 108,
    "filterCutoff": 100,
    "filterResonance": 30,
    "ampAttack": 0,
    "ampDecay": 28,
    "ampSustain": 0,
    "ampRelease": 22,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 15
  },
  {
    "name": "Vibraphone",
    "osc1Wave": 3,
    "osc1Level": 108,
    "filterCutoff": 102,
    "filterResonance": 20,
    "vp1Src": 2,
    "vp1Dst": 0,
    "vp1Int": 12,
    "lfo1Wave": 2,
    "lfo1Rate": 70,
    "ampAttack": 2,
    "ampDecay": 44,
    "ampSustain": 0,
    "ampRelease": 40,
    "vibratoIntensity": 42,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 18
  },
  {
    "name": "Xylophone",
    "osc1Wave": 0,
    "osc1Level": 110,
    "filterCutoff": 108,
    "filterResonance": 35,
    "filterEgInt": 32,
    "filterDecay": 18,
    "ampAttack": 0,
    "ampDecay": 22,
    "ampSustain": 0,
    "ampRelease": 18,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 20
  },
  {
    "name": "Soft Bell",
    "osc1Wave": 3,
    "osc1Level": 100,
    "filterCutoff": 96,
    "filterResonance": 20,
    "ampAttack": 2,
    "ampDecay": 72,
    "ampSustain": 0,
    "ampRelease": 68,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 20
  },
  {
    "name": "Steel Pan",
    "osc1Wave": 3,
    "osc2Wave": 0,
    "osc2Mod": 1,
    "osc1Level": 100,
    "osc2Level": 68,
    "filterCutoff": 100,
    "filterResonance": 35,
    "ampAttack": 0,
    "ampDecay": 40,
    "ampSustain": 0,
    "ampRelease": 32,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 20
  },
  {
    "name": "Ting",
    "osc1Wave": 3,
    "osc1Level": 108,
    "filterCutoff": 112,
    "filterResonance": 32,
    "filterEgInt": 28,
    "filterDecay": 15,
    "ampAttack": 0,
    "ampDecay": 18,
    "ampSustain": 0,
    "ampRelease": 18,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 15
  },
  {
    "name": "Chime",
    "osc1Wave": 3,
    "osc2Wave": 2,
    "osc1Level": 100,
    "osc2Level": 48,
    "filterCutoff": 102,
    "filterResonance": 25,
    "ampAttack": 0,
    "ampDecay": 82,
    "ampSustain": 0,
    "ampRelease": 72,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 15
  },
  {
    "name": "Hammond Full",
    "osc1Wave": 1,
    "osc2Wave": 1,
    "osc1Level": 105,
    "osc2Level": 75,
    "filterCutoff": 112,
    "filterResonance": 0,
    "ampAttack": 0,
    "ampSustain": 127,
    "ampRelease": 8,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 22
  },
  {
    "name": "Jazz Organ",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 100,
    "osc2Level": 65,
    "filterCutoff": 105,
    "filterResonance": 0,
    "ampAttack": 0,
    "ampSustain": 127,
    "ampRelease": 10,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 22
  },
  {
    "name": "Gospel Keys",
    "osc1Wave": 1,
    "osc2Wave": 2,
    "osc1Level": 102,
    "osc2Level": 72,
    "filterCutoff": 108,
    "filterResonance": 5,
    "ampAttack": 0,
    "ampSustain": 127,
    "ampRelease": 10,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Perc Organ",
    "osc1Wave": 1,
    "osc2Wave": 1,
    "osc1Level": 105,
    "osc2Level": 58,
    "filterCutoff": 110,
    "filterResonance": 8,
    "ampAttack": 0,
    "ampDecay": 45,
    "ampSustain": 60,
    "ampRelease": 12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 22
  },
  {
    "name": "Rock Organ",
    "osc1Wave": 1,
    "osc2Wave": 0,
    "osc1Level": 108,
    "osc2Level": 80,
    "filterCutoff": 115,
    "filterResonance": 0,
    "ampAttack": 0,
    "ampSustain": 127,
    "ampRelease": 8,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Pipe Organ",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 100,
    "osc2Level": 75,
    "filterCutoff": 100,
    "filterResonance": 0,
    "ampAttack": 8,
    "ampSustain": 127,
    "ampRelease": 18,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 22
  },
  {
    "name": "Rotary Slow",
    "osc1Wave": 1,
    "osc2Wave": 1,
    "osc1Level": 100,
    "osc2Level": 65,
    "filterCutoff": 105,
    "filterResonance": 5,
    "vp1Src": 2,
    "vp1Dst": 6,
    "vp1Int": 35,
    "lfo1Wave": 2,
    "lfo1Rate": 18,
    "ampAttack": 0,
    "ampSustain": 127,
    "ampRelease": 10,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 22
  },
  {
    "name": "Flute Organ",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 100,
    "osc2Level": 58,
    "filterCutoff": 95,
    "filterResonance": 8,
    "ampAttack": 3,
    "ampSustain": 127,
    "ampRelease": 12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 20
  },
  {
    "name": "Whistle",
    "osc1Wave": 3,
    "osc1Level": 110,
    "filterCutoff": 100,
    "filterResonance": 10,
    "vp1Src": 3,
    "vp1Dst": 0,
    "vp1Int": 22,
    "lfo2Wave": 2,
    "lfo2Rate": 70,
    "ampAttack": 8,
    "ampSustain": 100,
    "ampRelease": 45,
    "vibratoIntensity": 38,
    "vp2Src": 6,
    "vp2Dst": 0,
    "vp2Int": 28
  },
  {
    "name": "Dog Whistle",
    "osc1Wave": 3,
    "osc1Level": 108,
    "filterCutoff": 112,
    "filterResonance": 8,
    "vp1Src": 3,
    "vp1Dst": 0,
    "vp1Int": 28,
    "lfo2Wave": 2,
    "lfo2Rate": 62,
    "ampAttack": 4,
    "ampSustain": 100,
    "ampRelease": 35,
    "vibratoIntensity": 40,
    "vp2Src": 6,
    "vp2Dst": 0,
    "vp2Int": 30
  },
  {
    "name": "Slow Whistle",
    "osc1Wave": 3,
    "osc1Level": 108,
    "filterCutoff": 100,
    "filterResonance": 10,
    "vp1Src": 3,
    "vp1Dst": 0,
    "vp1Int": 18,
    "lfo2Wave": 2,
    "lfo2Rate": 70,
    "ampAttack": 10,
    "ampSustain": 100,
    "ampRelease": 50,
    "vibratoIntensity": 35,
    "vp2Src": 6,
    "vp2Dst": 0,
    "vp2Int": 22
  },
  {
    "name": "Wide Whistle",
    "osc1Wave": 3,
    "osc2Wave": 2,
    "osc1Level": 100,
    "osc2Level": 55,
    "filterCutoff": 98,
    "filterResonance": 12,
    "vp1Src": 3,
    "vp1Dst": 0,
    "vp1Int": 20,
    "lfo2Wave": 2,
    "lfo2Rate": 70,
    "ampAttack": 8,
    "ampSustain": 100,
    "ampRelease": 45,
    "vibratoIntensity": 38,
    "vp2Src": 6,
    "vp2Dst": 0,
    "vp2Int": 22
  },
  {
    "name": "Velvet Lead",
    "osc1Wave": 3,
    "osc2Wave": 0,
    "osc1Level": 100,
    "osc2Level": 30,
    "filterCutoff": 92,
    "filterResonance": 22,
    "filterEgInt": 18,
    "filterDecay": 40,
    "vp1Src": 3,
    "vp1Dst": 0,
    "vp1Int": 15,
    "lfo2Wave": 2,
    "lfo2Rate": 70,
    "ampAttack": 6,
    "ampSustain": 100,
    "ampRelease": 48,
    "vibratoIntensity": 36,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 20
  },
  {
    "name": "Smooth Lead",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 100,
    "osc2Level": 65,
    "filterCutoff": 88,
    "filterResonance": 20,
    "vp1Src": 3,
    "vp1Dst": 0,
    "vp1Int": 18,
    "lfo2Wave": 2,
    "lfo2Rate": 70,
    "ampAttack": 7,
    "ampSustain": 100,
    "ampRelease": 46,
    "vibratoIntensity": 38,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 20
  },
  {
    "name": "Warm Sine",
    "osc1Wave": 3,
    "osc1Level": 108,
    "filterCutoff": 90,
    "filterResonance": 15,
    "ampAttack": 6,
    "ampSustain": 100,
    "ampRelease": 46,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 18
  },
  {
    "name": "Sweet Sine",
    "osc1Wave": 3,
    "osc2Wave": 2,
    "osc1Level": 100,
    "osc2Level": 52,
    "filterCutoff": 92,
    "filterResonance": 14,
    "ampAttack": 7,
    "ampSustain": 100,
    "ampRelease": 50,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 20
  },
  {
    "name": "Sync Lead",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc2Mod": 2,
    "osc1Level": 102,
    "osc2Level": 52,
    "filterCutoff": 88,
    "filterResonance": 68,
    "filterEgInt": 42,
    "filterDecay": 30,
    "ampAttack": 2,
    "ampDecay": 50,
    "ampSustain": 85,
    "ampRelease": 32,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Warm Sync",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc2Mod": 2,
    "osc1Level": 100,
    "osc2Level": 48,
    "filterCutoff": 82,
    "filterResonance": 60,
    "filterEgInt": 36,
    "filterDecay": 32,
    "ampAttack": 3,
    "ampSustain": 92,
    "ampRelease": 35,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 32
  },
  {
    "name": "PWM Lead",
    "osc1Wave": 1,
    "osc1Level": 105,
    "filterCutoff": 90,
    "filterResonance": 35,
    "vp1Src": 2,
    "vp1Dst": 2,
    "vp1Int": 40,
    "lfo1Wave": 2,
    "lfo1Rate": 30,
    "ampAttack": 5,
    "ampSustain": 100,
    "ampRelease": 38,
    "vp2Src": 6,
    "vp2Dst": 2,
    "vp2Int": 35
  },
  {
    "name": "Saw Stack",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 98,
    "osc2Level": 92,
    "filterCutoff": 90,
    "filterResonance": 30,
    "ampAttack": 4,
    "ampSustain": 100,
    "ampRelease": 40,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Buzz Lead",
    "osc1Wave": 0,
    "osc1Level": 105,
    "filterCutoff": 72,
    "filterResonance": 110,
    "filterEgInt": 44,
    "filterDecay": 35,
    "ampAttack": 2,
    "ampDecay": 52,
    "ampSustain": 85,
    "ampRelease": 32,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Laser",
    "osc1Wave": 0,
    "osc1Level": 108,
    "filterCutoff": 100,
    "filterResonance": 55,
    "vp1Src": 1,
    "vp1Dst": 0,
    "vp1Int": -45,
    "ampAttack": 0,
    "ampDecay": 30,
    "ampSustain": 0,
    "ampRelease": 22,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Screamer",
    "osc1Wave": 0,
    "osc1Level": 100,
    "filterCutoff": 70,
    "filterResonance": 118,
    "filterEgInt": 40,
    "filterDecay": 35,
    "ampAttack": 2,
    "ampDecay": 48,
    "ampSustain": 78,
    "ampRelease": 30,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Warp Lead",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc2Mod": 2,
    "osc1Level": 105,
    "osc2Level": 62,
    "filterCutoff": 88,
    "filterResonance": 62,
    "filterEgInt": 44,
    "filterDecay": 35,
    "ampAttack": 1,
    "ampDecay": 42,
    "ampSustain": 85,
    "ampRelease": 32,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Soul Lead",
    "osc1Wave": 3,
    "osc2Wave": 2,
    "osc1Level": 102,
    "osc2Level": 32,
    "filterCutoff": 94,
    "filterResonance": 20,
    "ampAttack": 7,
    "ampSustain": 100,
    "ampRelease": 50,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 22
  },
  {
    "name": "Wah Lead",
    "osc1Wave": 0,
    "osc1Level": 108,
    "filterCutoff": 55,
    "filterResonance": 80,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 42,
    "lfo1Wave": 2,
    "lfo1Rate": 75,
    "ampAttack": 3,
    "ampSustain": 100,
    "ampRelease": 38,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 40
  },
  {
    "name": "Funky Lead",
    "osc1Wave": 0,
    "osc1Level": 108,
    "filterCutoff": 42,
    "filterResonance": 75,
    "filterEgInt": 54,
    "filterAttack": 0,
    "filterDecay": 38,
    "filterSustain": 10,
    "ampAttack": 2,
    "ampSustain": 92,
    "ampRelease": 38,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 40
  },
  {
    "name": "Cocked Wah",
    "osc1Wave": 0,
    "osc1Level": 108,
    "filterType": 2,
    "filterCutoff": 72,
    "filterResonance": 88,
    "ampAttack": 3,
    "ampSustain": 100,
    "ampRelease": 38,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 42
  },
  {
    "name": "Phaser Lead",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 95,
    "osc2Level": 88,
    "filterCutoff": 82,
    "filterResonance": 42,
    "vp1Src": 2,
    "vp1Dst": 6,
    "vp1Int": 40,
    "lfo1Wave": 2,
    "lfo1Rate": 18,
    "ampAttack": 4,
    "ampSustain": 100,
    "ampRelease": 42,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Groove Lead",
    "osc1Wave": 0,
    "osc1Level": 108,
    "filterCutoff": 68,
    "filterResonance": 55,
    "filterEgInt": 42,
    "filterDecay": 35,
    "ampAttack": 3,
    "ampSustain": 100,
    "ampRelease": 40,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Squeal",
    "osc1Wave": 0,
    "osc1Level": 100,
    "filterCutoff": 68,
    "filterResonance": 115,
    "filterEgInt": 38,
    "filterDecay": 35,
    "ampAttack": 3,
    "ampDecay": 52,
    "ampSustain": 85,
    "ampRelease": 38,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Moog Lead",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 102,
    "osc2Level": 40,
    "filterCutoff": 85,
    "filterResonance": 60,
    "filterEgInt": 35,
    "filterDecay": 40,
    "ampAttack": 5,
    "ampSustain": 100,
    "ampRelease": 46,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 20
  },
  {
    "name": "Rhodes Brite",
    "osc1Wave": 5,
    "osc1Level": 108,
    "filterCutoff": 100,
    "filterResonance": 30,
    "filterEgInt": 28,
    "filterDecay": 30,
    "ampAttack": 3,
    "ampDecay": 46,
    "ampSustain": 68,
    "ampRelease": 46,
    "vp1Src": 4,
    "vp1Dst": 5,
    "vp1Int": 38,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 28
  },
  {
    "name": "Rhodes Soft",
    "osc1Wave": 5,
    "osc1Level": 105,
    "filterCutoff": 82,
    "filterResonance": 20,
    "ampAttack": 5,
    "ampDecay": 54,
    "ampSustain": 72,
    "ampRelease": 52,
    "vp1Src": 4,
    "vp1Dst": 5,
    "vp1Int": 32,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Funk Keys",
    "osc1Wave": 5,
    "osc1Level": 105,
    "filterCutoff": 75,
    "filterResonance": 38,
    "filterEgInt": 32,
    "filterDecay": 28,
    "ampAttack": 4,
    "ampDecay": 50,
    "ampSustain": 70,
    "ampRelease": 44,
    "vp1Src": 4,
    "vp1Dst": 5,
    "vp1Int": 35,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Clavi Hard",
    "osc1Wave": 1,
    "osc1Level": 110,
    "filterCutoff": 108,
    "filterResonance": 55,
    "filterEgInt": 45,
    "filterDecay": 16,
    "ampAttack": 0,
    "ampDecay": 28,
    "ampSustain": 42,
    "ampRelease": 20,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Clavi Soft",
    "osc1Wave": 1,
    "osc1Level": 105,
    "filterCutoff": 92,
    "filterResonance": 40,
    "filterEgInt": 38,
    "filterDecay": 22,
    "ampAttack": 0,
    "ampDecay": 35,
    "ampSustain": 55,
    "ampRelease": 25,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 28
  },
  {
    "name": "Soul Keys",
    "osc1Wave": 5,
    "osc2Wave": 2,
    "osc1Level": 100,
    "osc2Level": 58,
    "filterCutoff": 85,
    "filterResonance": 24,
    "ampAttack": 6,
    "ampDecay": 52,
    "ampSustain": 74,
    "ampRelease": 52,
    "vp1Src": 4,
    "vp1Dst": 5,
    "vp1Int": 32,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Night Keys",
    "osc1Wave": 5,
    "osc1Level": 102,
    "filterCutoff": 72,
    "filterResonance": 22,
    "ampAttack": 7,
    "ampDecay": 56,
    "ampSustain": 70,
    "ampRelease": 56,
    "vp1Src": 4,
    "vp1Dst": 5,
    "vp1Int": 30,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Blue Note",
    "osc1Wave": 5,
    "osc2Wave": 2,
    "osc1Level": 98,
    "osc2Level": 48,
    "filterCutoff": 80,
    "filterResonance": 28,
    "filterEgInt": 20,
    "filterDecay": 35,
    "ampAttack": 5,
    "ampDecay": 52,
    "ampSustain": 72,
    "ampRelease": 54,
    "vp1Src": 4,
    "vp1Dst": 5,
    "vp1Int": 30,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Warm Pad",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 92,
    "osc2Level": 85,
    "filterCutoff": 72,
    "filterResonance": 18,
    "ampAttack": 25,
    "ampSustain": 100,
    "ampRelease": 82,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Lush",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 90,
    "osc2Level": 88,
    "filterCutoff": 75,
    "filterResonance": 20,
    "ampAttack": 22,
    "ampSustain": 100,
    "ampRelease": 84,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Velvet Pad",
    "osc1Wave": 2,
    "osc1Level": 90,
    "filterCutoff": 68,
    "filterResonance": 15,
    "ampAttack": 28,
    "ampSustain": 100,
    "ampRelease": 88,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Butter",
    "osc1Wave": 5,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 82,
    "filterCutoff": 76,
    "filterResonance": 16,
    "ampAttack": 22,
    "ampSustain": 100,
    "ampRelease": 84,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Cloud",
    "osc1Wave": 2,
    "osc2Wave": 0,
    "osc1Level": 88,
    "osc2Level": 82,
    "filterCutoff": 65,
    "filterResonance": 14,
    "ampAttack": 35,
    "ampSustain": 100,
    "ampRelease": 92,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Silk",
    "osc1Wave": 3,
    "osc2Wave": 2,
    "osc1Level": 90,
    "osc2Level": 78,
    "filterCutoff": 72,
    "filterResonance": 16,
    "ampAttack": 24,
    "ampSustain": 100,
    "ampRelease": 84,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Juno Pad",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 90,
    "osc2Level": 84,
    "filterCutoff": 78,
    "filterResonance": 24,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 15,
    "lfo1Wave": 2,
    "lfo1Rate": 22,
    "ampAttack": 22,
    "ampSustain": 100,
    "ampRelease": 82,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Comfort",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 86,
    "filterCutoff": 70,
    "filterResonance": 14,
    "ampAttack": 30,
    "ampSustain": 100,
    "ampRelease": 90,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Breathing",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 90,
    "osc2Level": 82,
    "filterCutoff": 72,
    "filterResonance": 20,
    "vp1Src": 2,
    "vp1Dst": 5,
    "vp1Int": 35,
    "lfo1Wave": 2,
    "lfo1Rate": 14,
    "ampAttack": 22,
    "ampSustain": 100,
    "ampRelease": 80,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Swell",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 84,
    "filterCutoff": 52,
    "filterResonance": 22,
    "filterEgInt": 48,
    "filterAttack": 22,
    "filterDecay": 72,
    "ampAttack": 20,
    "ampSustain": 100,
    "ampRelease": 82,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 40
  },
  {
    "name": "Morphing Pad",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 82,
    "filterCutoff": 58,
    "filterResonance": 28,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 30,
    "lfo1Wave": 2,
    "lfo1Rate": 12,
    "ampAttack": 24,
    "ampSustain": 100,
    "ampRelease": 84,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 38
  },
  {
    "name": "Rolling",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 90,
    "osc2Level": 80,
    "filterCutoff": 65,
    "filterResonance": 32,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 32,
    "lfo1Wave": 2,
    "lfo1Rate": 18,
    "ampAttack": 20,
    "ampSustain": 100,
    "ampRelease": 78,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Tidal",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 84,
    "filterCutoff": 60,
    "filterResonance": 22,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 28,
    "lfo1Wave": 2,
    "lfo1Rate": 9,
    "ampAttack": 30,
    "ampSustain": 100,
    "ampRelease": 92,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Living Pad",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 80,
    "filterCutoff": 65,
    "filterResonance": 30,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 28,
    "lfo1Wave": 2,
    "lfo1Rate": 10,
    "ampAttack": 24,
    "ampSustain": 100,
    "ampRelease": 82,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 35
  },
  {
    "name": "Waves",
    "osc1Wave": 2,
    "osc1Level": 90,
    "filterCutoff": 68,
    "filterResonance": 25,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 30,
    "lfo1Wave": 2,
    "lfo1Rate": 16,
    "ampAttack": 28,
    "ampSustain": 100,
    "ampRelease": 88,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Current",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 88,
    "osc2Level": 82,
    "filterCutoff": 62,
    "filterResonance": 28,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 30,
    "lfo1Wave": 2,
    "lfo1Rate": 14,
    "ampAttack": 24,
    "ampSustain": 100,
    "ampRelease": 84,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Strings",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 90,
    "osc2Level": 86,
    "filterCutoff": 80,
    "filterResonance": 20,
    "ampAttack": 20,
    "ampSustain": 100,
    "ampRelease": 78,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Ensemble",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 88,
    "osc2Level": 88,
    "filterCutoff": 78,
    "filterResonance": 20,
    "ampAttack": 22,
    "ampSustain": 100,
    "ampRelease": 80,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Cello",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 90,
    "osc2Level": 72,
    "filterCutoff": 70,
    "filterResonance": 22,
    "ampAttack": 25,
    "ampSustain": 100,
    "ampRelease": 80,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Viola",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 88,
    "osc2Level": 84,
    "filterCutoff": 78,
    "filterResonance": 20,
    "ampAttack": 20,
    "ampSustain": 100,
    "ampRelease": 78,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Violin Hi",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 88,
    "osc2Level": 86,
    "filterCutoff": 85,
    "filterResonance": 20,
    "ampAttack": 25,
    "ampSustain": 100,
    "ampRelease": 72,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Pizzicato",
    "osc1Wave": 0,
    "osc1Level": 108,
    "filterCutoff": 92,
    "filterResonance": 30,
    "filterEgInt": 35,
    "filterDecay": 20,
    "ampAttack": 0,
    "ampDecay": 40,
    "ampSustain": 0,
    "ampRelease": 30,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Slow Bow",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 88,
    "osc2Level": 84,
    "filterCutoff": 72,
    "filterResonance": 20,
    "ampAttack": 38,
    "ampSustain": 100,
    "ampRelease": 90,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Full Bow",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 86,
    "filterCutoff": 76,
    "filterResonance": 20,
    "ampAttack": 24,
    "ampSustain": 100,
    "ampRelease": 82,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Deep Space",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 85,
    "osc2Level": 84,
    "filterCutoff": 58,
    "filterResonance": 20,
    "ampAttack": 38,
    "ampSustain": 100,
    "ampRelease": 100,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Cosmos",
    "osc1Wave": 3,
    "osc2Wave": 2,
    "osc1Level": 85,
    "osc2Level": 78,
    "filterCutoff": 60,
    "filterResonance": 18,
    "ampAttack": 35,
    "ampSustain": 100,
    "ampRelease": 100,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Nebula",
    "osc1Wave": 2,
    "osc1Level": 82,
    "noiseLevel": 28,
    "filterCutoff": 56,
    "filterResonance": 22,
    "ampAttack": 40,
    "ampSustain": 100,
    "ampRelease": 100,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Star Field",
    "osc1Wave": 3,
    "osc2Wave": 0,
    "osc1Level": 85,
    "osc2Level": 72,
    "filterCutoff": 66,
    "filterResonance": 20,
    "ampAttack": 30,
    "ampSustain": 100,
    "ampRelease": 96,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Void",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 80,
    "osc2Level": 82,
    "filterCutoff": 50,
    "filterResonance": 18,
    "ampAttack": 45,
    "ampSustain": 100,
    "ampRelease": 100,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Aurora",
    "osc1Wave": 2,
    "osc1Level": 85,
    "filterCutoff": 54,
    "filterResonance": 25,
    "filterEgInt": 42,
    "filterAttack": 28,
    "filterDecay": 82,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 24,
    "lfo1Wave": 2,
    "lfo1Rate": 8,
    "ampAttack": 32,
    "ampSustain": 100,
    "ampRelease": 100,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 38
  },
  {
    "name": "Horizon",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 85,
    "osc2Level": 82,
    "filterCutoff": 64,
    "filterResonance": 18,
    "ampAttack": 28,
    "ampSustain": 100,
    "ampRelease": 94,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Dusk",
    "osc1Wave": 2,
    "osc2Wave": 0,
    "osc1Level": 85,
    "osc2Level": 78,
    "filterCutoff": 60,
    "filterResonance": 20,
    "ampAttack": 30,
    "ampSustain": 100,
    "ampRelease": 96,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Twilight",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 86,
    "filterCutoff": 68,
    "filterResonance": 16,
    "ampAttack": 26,
    "ampSustain": 100,
    "ampRelease": 90,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Sunset",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 84,
    "filterCutoff": 70,
    "filterResonance": 18,
    "ampAttack": 24,
    "ampSustain": 100,
    "ampRelease": 87,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Dawn",
    "osc1Wave": 2,
    "osc2Wave": 0,
    "osc1Level": 88,
    "osc2Level": 80,
    "filterCutoff": 74,
    "filterResonance": 18,
    "ampAttack": 22,
    "ampSustain": 100,
    "ampRelease": 84,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Blue Hour",
    "osc1Wave": 3,
    "osc2Wave": 2,
    "osc1Level": 85,
    "osc2Level": 82,
    "filterCutoff": 65,
    "filterResonance": 16,
    "ampAttack": 30,
    "ampSustain": 100,
    "ampRelease": 92,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Evening",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 84,
    "filterCutoff": 68,
    "filterResonance": 16,
    "ampAttack": 27,
    "ampSustain": 100,
    "ampRelease": 90,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Midnight",
    "osc1Wave": 2,
    "osc2Wave": 0,
    "osc1Level": 85,
    "osc2Level": 82,
    "filterCutoff": 60,
    "filterResonance": 18,
    "ampAttack": 32,
    "ampSustain": 100,
    "ampRelease": 94,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "First Light",
    "osc1Wave": 3,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 80,
    "filterCutoff": 72,
    "filterResonance": 16,
    "ampAttack": 24,
    "ampSustain": 100,
    "ampRelease": 84,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Golden Hour",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 84,
    "filterCutoff": 72,
    "filterResonance": 20,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 18,
    "lfo1Wave": 2,
    "lfo1Rate": 10,
    "ampAttack": 24,
    "ampSustain": 100,
    "ampRelease": 87,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Resonant Pad",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 80,
    "filterCutoff": 56,
    "filterResonance": 72,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 30,
    "lfo1Wave": 2,
    "lfo1Rate": 70,
    "ampAttack": 24,
    "ampSustain": 100,
    "ampRelease": 84,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 40
  },
  {
    "name": "Rezo",
    "osc1Wave": 0,
    "osc1Level": 90,
    "filterCutoff": 58,
    "filterResonance": 88,
    "filterEgInt": 40,
    "filterAttack": 14,
    "filterDecay": 68,
    "ampAttack": 22,
    "ampSustain": 100,
    "ampRelease": 82,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 40
  },
  {
    "name": "Filtered Pad",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 80,
    "filterCutoff": 50,
    "filterResonance": 78,
    "filterEgInt": 45,
    "filterAttack": 18,
    "filterDecay": 72,
    "ampAttack": 24,
    "ampSustain": 100,
    "ampRelease": 84,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 40
  },
  {
    "name": "Sweep Pad",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 80,
    "filterCutoff": 44,
    "filterResonance": 70,
    "filterEgInt": 55,
    "filterAttack": 20,
    "filterDecay": 82,
    "ampAttack": 22,
    "ampSustain": 100,
    "ampRelease": 87,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 42
  },
  {
    "name": "Bloom",
    "osc1Wave": 2,
    "osc1Level": 88,
    "filterCutoff": 46,
    "filterResonance": 75,
    "filterEgInt": 58,
    "filterAttack": 22,
    "filterDecay": 92,
    "ampAttack": 28,
    "ampSustain": 100,
    "ampRelease": 92,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 42
  },
  {
    "name": "Peak Pad",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 88,
    "osc2Level": 80,
    "filterCutoff": 60,
    "filterResonance": 102,
    "filterEgInt": 38,
    "filterAttack": 12,
    "filterDecay": 62,
    "ampAttack": 22,
    "ampSustain": 100,
    "ampRelease": 82,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Crystal Pad",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 82,
    "filterCutoff": 82,
    "filterResonance": 62,
    "filterEgInt": 30,
    "filterDecay": 52,
    "ampAttack": 20,
    "ampSustain": 100,
    "ampRelease": 80,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Liquid",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 82,
    "filterCutoff": 58,
    "filterResonance": 68,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 32,
    "lfo1Wave": 2,
    "lfo1Rate": 16,
    "ampAttack": 24,
    "ampSustain": 100,
    "ampRelease": 84,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 40
  },
  {
    "name": "Wide Pad",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 90,
    "osc2Level": 88,
    "filterCutoff": 75,
    "filterResonance": 20,
    "ampAttack": 24,
    "ampSustain": 100,
    "ampRelease": 84,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Shimmer",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 84,
    "filterCutoff": 78,
    "filterResonance": 22,
    "ampAttack": 22,
    "ampSustain": 100,
    "ampRelease": 82,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Chorus Pad",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 84,
    "filterCutoff": 76,
    "filterResonance": 20,
    "ampAttack": 24,
    "ampSustain": 100,
    "ampRelease": 84,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Lush Wide",
    "osc1Wave": 2,
    "osc2Wave": 0,
    "osc1Level": 88,
    "osc2Level": 86,
    "filterCutoff": 72,
    "filterResonance": 18,
    "ampAttack": 28,
    "ampSustain": 100,
    "ampRelease": 87,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Floating",
    "osc1Wave": 3,
    "osc2Wave": 2,
    "osc1Level": 85,
    "osc2Level": 84,
    "filterCutoff": 70,
    "filterResonance": 16,
    "ampAttack": 30,
    "ampSustain": 100,
    "ampRelease": 90,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Veil",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 82,
    "osc2Level": 82,
    "filterCutoff": 65,
    "filterResonance": 14,
    "ampAttack": 34,
    "ampSustain": 100,
    "ampRelease": 94,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Haze",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 85,
    "osc2Level": 82,
    "filterCutoff": 68,
    "filterResonance": 18,
    "ampAttack": 30,
    "ampSustain": 100,
    "ampRelease": 90,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Diffuse",
    "osc1Wave": 2,
    "osc2Wave": 0,
    "osc1Level": 85,
    "osc2Level": 84,
    "filterCutoff": 70,
    "filterResonance": 16,
    "ampAttack": 32,
    "ampSustain": 100,
    "ampRelease": 92,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Dub Pad",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 90,
    "osc2Level": 78,
    "filterCutoff": 70,
    "filterResonance": 22,
    "ampAttack": 25,
    "ampSustain": 100,
    "ampRelease": 78,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Echo Pad",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 80,
    "filterCutoff": 68,
    "filterResonance": 20,
    "ampAttack": 20,
    "ampSustain": 100,
    "ampRelease": 80,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Dub Chord",
    "osc1Wave": 0,
    "osc2Wave": 1,
    "osc1Level": 88,
    "osc2Level": 74,
    "filterCutoff": 72,
    "filterResonance": 24,
    "ampAttack": 25,
    "ampDecay": 52,
    "ampSustain": 74,
    "ampRelease": 67,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Space Echo",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 85,
    "osc2Level": 82,
    "filterCutoff": 65,
    "filterResonance": 20,
    "ampAttack": 22,
    "ampSustain": 100,
    "ampRelease": 87,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Reverb Pad",
    "osc1Wave": 3,
    "osc2Wave": 2,
    "osc1Level": 85,
    "osc2Level": 80,
    "filterCutoff": 68,
    "filterResonance": 18,
    "ampAttack": 24,
    "ampSustain": 100,
    "ampRelease": 92,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Dub Wide",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 88,
    "osc2Level": 86,
    "filterCutoff": 70,
    "filterResonance": 22,
    "ampAttack": 20,
    "ampSustain": 100,
    "ampRelease": 84,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Echo Drift",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 85,
    "osc2Level": 82,
    "filterCutoff": 65,
    "filterResonance": 20,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 20,
    "lfo1Wave": 2,
    "lfo1Rate": 8,
    "ampAttack": 27,
    "ampSustain": 100,
    "ampRelease": 90,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Wet Pad",
    "osc1Wave": 2,
    "osc2Wave": 0,
    "osc1Level": 85,
    "osc2Level": 82,
    "filterCutoff": 68,
    "filterResonance": 18,
    "ampAttack": 24,
    "ampSustain": 100,
    "ampRelease": 90,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Dub Echo",
    "osc1Wave": 0,
    "osc1Level": 105,
    "filterCutoff": 70,
    "filterResonance": 30,
    "ampAttack": 3,
    "ampDecay": 55,
    "ampSustain": 62,
    "ampRelease": 58,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Skank Echo",
    "osc1Wave": 0,
    "osc2Wave": 1,
    "osc1Level": 100,
    "osc2Level": 58,
    "filterCutoff": 85,
    "filterResonance": 38,
    "filterEgInt": 32,
    "filterDecay": 25,
    "ampAttack": 1,
    "ampDecay": 30,
    "ampSustain": 0,
    "ampRelease": 25,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Dub Note",
    "osc1Wave": 2,
    "osc1Level": 102,
    "filterCutoff": 74,
    "filterResonance": 32,
    "ampAttack": 3,
    "ampDecay": 45,
    "ampSustain": 52,
    "ampRelease": 52,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Deep Dub",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 100,
    "osc2Level": 60,
    "filterCutoff": 62,
    "filterResonance": 30,
    "ampAttack": 5,
    "ampSustain": 82,
    "ampRelease": 67,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Delay Fade",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 95,
    "osc2Level": 78,
    "filterCutoff": 70,
    "filterResonance": 24,
    "ampAttack": 5,
    "ampDecay": 62,
    "ampSustain": 42,
    "ampRelease": 67,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Dub Stab",
    "osc1Wave": 0,
    "osc2Wave": 1,
    "osc1Level": 102,
    "osc2Level": 62,
    "filterCutoff": 88,
    "filterResonance": 45,
    "filterEgInt": 38,
    "filterDecay": 20,
    "ampAttack": 0,
    "ampDecay": 28,
    "ampSustain": 0,
    "ampRelease": 22,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Echo Lead",
    "osc1Wave": 0,
    "osc1Level": 105,
    "filterCutoff": 88,
    "filterResonance": 35,
    "ampAttack": 3,
    "ampSustain": 92,
    "ampRelease": 44,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Dub Organ",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 95,
    "osc2Level": 68,
    "filterCutoff": 80,
    "filterResonance": 24,
    "ampAttack": 5,
    "ampSustain": 100,
    "ampRelease": 52,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Bubbling",
    "osc1Wave": 0,
    "osc1Level": 108,
    "filterCutoff": 50,
    "filterResonance": 100,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 52,
    "lfo1Wave": 2,
    "lfo1Rate": 72,
    "ampAttack": 2,
    "ampSustain": 100,
    "ampRelease": 40,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 45
  },
  {
    "name": "Gurgle",
    "osc1Wave": 0,
    "osc1Level": 108,
    "filterCutoff": 46,
    "filterResonance": 108,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 56,
    "lfo1Wave": 2,
    "lfo1Rate": 62,
    "ampAttack": 2,
    "ampSustain": 100,
    "ampRelease": 38,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 45
  },
  {
    "name": "Percolate",
    "osc1Wave": 0,
    "osc1Level": 105,
    "filterCutoff": 53,
    "filterResonance": 98,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 48,
    "lfo1Wave": 2,
    "lfo1Rate": 75,
    "ampAttack": 1,
    "ampSustain": 100,
    "ampRelease": 35,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 45
  },
  {
    "name": "Fizz",
    "osc1Wave": 1,
    "osc1Level": 100,
    "filterCutoff": 60,
    "filterResonance": 92,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 45,
    "lfo1Wave": 2,
    "lfo1Rate": 82,
    "ampAttack": 1,
    "ampSustain": 100,
    "ampRelease": 32,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 45
  },
  {
    "name": "Drip",
    "osc1Wave": 3,
    "osc1Level": 100,
    "filterCutoff": 48,
    "filterResonance": 102,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 52,
    "lfo1Wave": 2,
    "lfo1Rate": 50,
    "ampAttack": 2,
    "ampSustain": 100,
    "ampRelease": 45,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 42
  },
  {
    "name": "Boil",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 105,
    "osc2Level": 78,
    "filterCutoff": 48,
    "filterResonance": 105,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 55,
    "lfo1Wave": 3,
    "lfo1Rate": 72,
    "ampAttack": 1,
    "ampSustain": 100,
    "ampRelease": 35,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 45
  },
  {
    "name": "Brook",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 95,
    "osc2Level": 78,
    "filterCutoff": 56,
    "filterResonance": 80,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 44,
    "lfo1Wave": 2,
    "lfo1Rate": 58,
    "ampAttack": 3,
    "ampSustain": 100,
    "ampRelease": 45,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 42
  },
  {
    "name": "Ocean",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 90,
    "osc2Level": 82,
    "filterCutoff": 54,
    "filterResonance": 68,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 38,
    "lfo1Wave": 2,
    "lfo1Rate": 45,
    "ampAttack": 8,
    "ampSustain": 100,
    "ampRelease": 62,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 42
  },
  {
    "name": "Psy Chorus",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 92,
    "osc2Level": 88,
    "filterCutoff": 78,
    "filterResonance": 32,
    "ampAttack": 5,
    "ampSustain": 100,
    "ampRelease": 50,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 35
  },
  {
    "name": "Spiral FX",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 90,
    "osc2Level": 82,
    "filterCutoff": 62,
    "filterResonance": 78,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 42,
    "lfo1Wave": 2,
    "lfo1Rate": 52,
    "ampAttack": 4,
    "ampSustain": 100,
    "ampRelease": 48,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 42
  },
  {
    "name": "Trippy",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 90,
    "osc2Level": 82,
    "filterCutoff": 60,
    "filterResonance": 82,
    "vp1Src": 2,
    "vp1Dst": 0,
    "vp1Int": 15,
    "lfo1Wave": 2,
    "lfo1Rate": 75,
    "ampAttack": 5,
    "ampSustain": 100,
    "ampRelease": 50,
    "vibratoIntensity": 42,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 40
  },
  {
    "name": "Shpongle",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 86,
    "filterCutoff": 65,
    "filterResonance": 60,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 30,
    "lfo1Wave": 2,
    "lfo1Rate": 20,
    "ampAttack": 8,
    "ampSustain": 100,
    "ampRelease": 58,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 38
  },
  {
    "name": "Wavering",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 90,
    "osc2Level": 82,
    "filterCutoff": 70,
    "filterResonance": 32,
    "vp1Src": 2,
    "vp1Dst": 0,
    "vp1Int": 20,
    "lfo1Wave": 2,
    "lfo1Rate": 70,
    "ampAttack": 6,
    "ampSustain": 100,
    "ampRelease": 52,
    "vibratoIntensity": 44,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 30
  },
  {
    "name": "Drift",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 84,
    "filterCutoff": 65,
    "filterResonance": 24,
    "vp1Src": 2,
    "vp1Dst": 0,
    "vp1Int": 10,
    "lfo1Wave": 2,
    "lfo1Rate": 70,
    "ampAttack": 12,
    "ampSustain": 100,
    "ampRelease": 65,
    "vibratoIntensity": 38,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 30
  },
  {
    "name": "Floating FX",
    "osc1Wave": 3,
    "osc2Wave": 2,
    "osc1Level": 85,
    "osc2Level": 80,
    "filterCutoff": 68,
    "filterResonance": 20,
    "ampAttack": 20,
    "ampSustain": 100,
    "ampRelease": 82,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Vortex",
    "osc1Wave": 0,
    "osc1Level": 105,
    "filterCutoff": 52,
    "filterResonance": 95,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 52,
    "lfo1Wave": 2,
    "lfo1Rate": 78,
    "ampAttack": 2,
    "ampSustain": 100,
    "ampRelease": 38,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 45
  },
  {
    "name": "Arp Note",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 102,
    "osc2Level": 56,
    "filterCutoff": 92,
    "filterResonance": 35,
    "filterEgInt": 30,
    "filterDecay": 22,
    "ampAttack": 1,
    "ampDecay": 28,
    "ampSustain": 52,
    "ampRelease": 22,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Stab Arp",
    "osc1Wave": 0,
    "osc1Level": 108,
    "filterCutoff": 98,
    "filterResonance": 45,
    "filterEgInt": 38,
    "filterDecay": 18,
    "ampAttack": 0,
    "ampDecay": 22,
    "ampSustain": 0,
    "ampRelease": 18,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Bright Arp",
    "osc1Wave": 0,
    "osc2Wave": 1,
    "osc1Level": 102,
    "osc2Level": 46,
    "filterCutoff": 104,
    "filterResonance": 40,
    "filterEgInt": 32,
    "filterDecay": 18,
    "ampAttack": 0,
    "ampDecay": 25,
    "ampSustain": 20,
    "ampRelease": 20,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Dark Arp",
    "osc1Wave": 0,
    "osc1Level": 105,
    "filterCutoff": 70,
    "filterResonance": 50,
    "filterEgInt": 40,
    "filterDecay": 25,
    "ampAttack": 1,
    "ampDecay": 30,
    "ampSustain": 32,
    "ampRelease": 25,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Acid Arp",
    "osc1Wave": 0,
    "osc1Level": 108,
    "filterCutoff": 52,
    "filterResonance": 92,
    "filterEgInt": 52,
    "filterDecay": 22,
    "ampAttack": 0,
    "ampDecay": 25,
    "ampSustain": 40,
    "ampRelease": 20,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Bell Arp",
    "osc1Wave": 3,
    "osc2Wave": 0,
    "osc2Mod": 1,
    "osc1Level": 100,
    "osc2Level": 60,
    "filterCutoff": 100,
    "filterResonance": 30,
    "ampAttack": 0,
    "ampDecay": 45,
    "ampSustain": 0,
    "ampRelease": 35,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 20
  },
  {
    "name": "Gate Arp",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 100,
    "osc2Level": 60,
    "filterCutoff": 88,
    "filterResonance": 38,
    "vp1Src": 2,
    "vp1Dst": 5,
    "vp1Int": 45,
    "lfo1Wave": 1,
    "lfo1Rate": 60,
    "ampAttack": 1,
    "ampSustain": 100,
    "ampRelease": 20,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 35
  },
  {
    "name": "Bass Arp",
    "osc1Wave": 0,
    "osc1Level": 110,
    "filterCutoff": 76,
    "filterResonance": 45,
    "filterEgInt": 40,
    "filterDecay": 22,
    "ampAttack": 0,
    "ampDecay": 32,
    "ampSustain": 30,
    "ampRelease": 22,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Classic Stab",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 98,
    "osc2Level": 90,
    "filterCutoff": 96,
    "filterResonance": 45,
    "filterEgInt": 35,
    "filterDecay": 18,
    "ampAttack": 0,
    "ampDecay": 25,
    "ampSustain": 0,
    "ampRelease": 18,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "House Stab",
    "osc1Wave": 0,
    "osc2Wave": 1,
    "osc1Level": 95,
    "osc2Level": 80,
    "filterCutoff": 90,
    "filterResonance": 38,
    "filterEgInt": 30,
    "filterDecay": 20,
    "ampAttack": 0,
    "ampDecay": 28,
    "ampSustain": 0,
    "ampRelease": 20,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Psy Stab",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc2Mod": 2,
    "osc1Level": 100,
    "osc2Level": 58,
    "filterCutoff": 92,
    "filterResonance": 65,
    "filterEgInt": 40,
    "filterDecay": 18,
    "ampAttack": 0,
    "ampDecay": 22,
    "ampSustain": 0,
    "ampRelease": 16,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Techno Hit",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 102,
    "osc2Level": 88,
    "filterCutoff": 100,
    "filterResonance": 52,
    "filterEgInt": 35,
    "filterDecay": 16,
    "ampAttack": 0,
    "ampDecay": 22,
    "ampSustain": 0,
    "ampRelease": 15,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Bell Hit",
    "osc1Wave": 3,
    "osc2Wave": 0,
    "osc2Mod": 1,
    "osc1Level": 100,
    "osc2Level": 74,
    "filterCutoff": 100,
    "filterResonance": 35,
    "ampAttack": 0,
    "ampDecay": 40,
    "ampSustain": 0,
    "ampRelease": 32,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 20
  },
  {
    "name": "Chord Hit",
    "osc1Wave": 0,
    "osc2Wave": 1,
    "osc1Level": 95,
    "osc2Level": 82,
    "filterCutoff": 88,
    "filterResonance": 30,
    "filterEgInt": 28,
    "filterDecay": 20,
    "ampAttack": 2,
    "ampDecay": 32,
    "ampSustain": 0,
    "ampRelease": 22,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Brass Hit",
    "osc1Wave": 0,
    "osc1Level": 110,
    "filterCutoff": 100,
    "filterResonance": 40,
    "filterEgInt": 38,
    "filterDecay": 18,
    "ampAttack": 2,
    "ampDecay": 35,
    "ampSustain": 20,
    "ampRelease": 22,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Pluck Hit",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 105,
    "osc2Level": 54,
    "filterCutoff": 102,
    "filterResonance": 48,
    "filterEgInt": 40,
    "filterDecay": 18,
    "ampAttack": 0,
    "ampDecay": 25,
    "ampSustain": 0,
    "ampRelease": 18,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Filter Rise",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 105,
    "osc2Level": 82,
    "filterCutoff": 22,
    "filterResonance": 68,
    "filterEgInt": 62,
    "filterAttack": 82,
    "filterDecay": 100,
    "ampAttack": 0,
    "ampSustain": 100,
    "ampRelease": 35,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 45
  },
  {
    "name": "Pitch Rise",
    "osc1Wave": 0,
    "osc1Level": 108,
    "filterCutoff": 88,
    "filterResonance": 35,
    "vp1Src": 1,
    "vp1Dst": 0,
    "vp1Int": 55,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 72,
    "ampRelease": 42,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 40
  },
  {
    "name": "Noise Rise",
    "osc1Wave": 6,
    "osc1Level": 100,
    "noiseLevel": 90,
    "filterCutoff": 20,
    "filterResonance": 60,
    "filterEgInt": 62,
    "filterAttack": 92,
    "filterDecay": 100,
    "ampAttack": 10,
    "ampSustain": 100,
    "ampRelease": 42,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 45
  },
  {
    "name": "Sub Drop",
    "osc1Wave": 3,
    "osc1Level": 115,
    "filterCutoff": 58,
    "filterResonance": 18,
    "vp1Src": 1,
    "vp1Dst": 0,
    "vp1Int": -38,
    "ampAttack": 0,
    "ampDecay": 92,
    "ampSustain": 52,
    "ampRelease": 62,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Slow Rise",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 98,
    "osc2Level": 82,
    "filterCutoff": 18,
    "filterResonance": 58,
    "filterEgInt": 60,
    "filterAttack": 100,
    "filterDecay": 100,
    "ampAttack": 15,
    "ampSustain": 100,
    "ampRelease": 52,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 45
  },
  {
    "name": "Rev Env",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 100,
    "osc2Level": 80,
    "filterCutoff": 65,
    "filterResonance": 38,
    "ampAttack": 100,
    "ampDecay": 42,
    "ampSustain": 82,
    "ampRelease": 57,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 40
  },
  {
    "name": "Drop FX",
    "osc1Wave": 0,
    "osc1Level": 108,
    "filterCutoff": 90,
    "filterResonance": 48,
    "vp1Src": 1,
    "vp1Dst": 0,
    "vp1Int": -55,
    "ampAttack": 0,
    "ampDecay": 45,
    "ampSustain": 0,
    "ampRelease": 28,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 40
  },
  {
    "name": "Wave Rise",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 95,
    "osc2Level": 84,
    "filterCutoff": 28,
    "filterResonance": 72,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 48,
    "lfo1Wave": 2,
    "lfo1Rate": 55,
    "filterEgInt": 52,
    "filterAttack": 72,
    "filterDecay": 100,
    "ampAttack": 5,
    "ampSustain": 100,
    "ampRelease": 47,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 45
  },
  {
    "name": "Alien Vox",
    "osc1Wave": 4,
    "osc1Level": 108,
    "filterCutoff": 68,
    "filterResonance": 88,
    "filterEgInt": 44,
    "filterDecay": 50,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 34,
    "lfo1Wave": 2,
    "lfo1Rate": 75,
    "ampAttack": 5,
    "ampSustain": 92,
    "ampRelease": 54,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 45
  },
  {
    "name": "Ring Planet",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc2Mod": 1,
    "osc1Level": 100,
    "osc2Level": 82,
    "filterCutoff": 66,
    "filterResonance": 72,
    "filterEgInt": 42,
    "filterDecay": 44,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 38,
    "lfo1Wave": 2,
    "lfo1Rate": 75,
    "ampAttack": 3,
    "ampSustain": 92,
    "ampRelease": 52,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 40
  },
  {
    "name": "S&H Alien",
    "osc1Wave": 1,
    "osc1Level": 102,
    "filterCutoff": 75,
    "filterResonance": 68,
    "vp1Src": 2,
    "vp1Dst": 0,
    "vp1Int": 38,
    "lfo1Wave": 3,
    "lfo1Rate": 72,
    "ampAttack": 1,
    "ampDecay": 35,
    "ampSustain": 68,
    "ampRelease": 28,
    "vibratoIntensity": 45,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 40
  },
  {
    "name": "Glitch",
    "osc1Wave": 1,
    "osc2Wave": 1,
    "osc1Level": 100,
    "osc2Level": 82,
    "filterCutoff": 80,
    "filterResonance": 62,
    "vp1Src": 2,
    "vp1Dst": 0,
    "vp1Int": 42,
    "lfo1Wave": 3,
    "lfo1Rate": 88,
    "ampAttack": 0,
    "ampDecay": 30,
    "ampSustain": 58,
    "ampRelease": 22,
    "vibratoIntensity": 43,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 40
  },
  {
    "name": "Metal Hit",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc2Mod": 1,
    "osc1Level": 102,
    "osc2Level": 90,
    "filterCutoff": 92,
    "filterResonance": 65,
    "filterEgInt": 40,
    "filterDecay": 22,
    "ampAttack": 0,
    "ampDecay": 30,
    "ampSustain": 0,
    "ampRelease": 22,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Alien Talk",
    "osc1Wave": 4,
    "osc2Wave": 1,
    "osc1Level": 100,
    "osc2Level": 58,
    "filterType": 2,
    "filterCutoff": 65,
    "filterResonance": 92,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 42,
    "lfo1Wave": 2,
    "lfo1Rate": 80,
    "ampAttack": 4,
    "ampSustain": 94,
    "ampRelease": 50,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 45
  },
  {
    "name": "Laser FX",
    "osc1Wave": 0,
    "osc1Level": 108,
    "filterCutoff": 100,
    "filterResonance": 52,
    "vp1Src": 1,
    "vp1Dst": 0,
    "vp1Int": 52,
    "ampAttack": 0,
    "ampDecay": 28,
    "ampSustain": 0,
    "ampRelease": 18,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 35
  },
  {
    "name": "Siren",
    "osc1Wave": 0,
    "osc1Level": 108,
    "filterCutoff": 92,
    "filterResonance": 35,
    "vp1Src": 2,
    "vp1Dst": 0,
    "vp1Int": 54,
    "lfo1Wave": 2,
    "lfo1Rate": 70,
    "ampAttack": 5,
    "ampSustain": 100,
    "ampRelease": 35,
    "vibratoIntensity": 40,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 35
  },
  {
    "name": "Drone Low",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 92,
    "osc2Level": 86,
    "filterCutoff": 45,
    "filterResonance": 30,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 22,
    "lfo1Wave": 2,
    "lfo1Rate": 6,
    "ampAttack": 58,
    "ampSustain": 100,
    "ampRelease": 100,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Drone Mid",
    "osc1Wave": 2,
    "osc2Wave": 0,
    "osc1Level": 88,
    "osc2Level": 86,
    "filterCutoff": 65,
    "filterResonance": 28,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 20,
    "lfo1Wave": 2,
    "lfo1Rate": 8,
    "ampAttack": 50,
    "ampSustain": 100,
    "ampRelease": 100,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Drone High",
    "osc1Wave": 2,
    "osc2Wave": 0,
    "osc1Level": 85,
    "osc2Level": 86,
    "filterCutoff": 75,
    "filterResonance": 25,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 20,
    "lfo1Wave": 2,
    "lfo1Rate": 9,
    "ampAttack": 47,
    "ampSustain": 100,
    "ampRelease": 100,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Wind",
    "osc1Wave": 6,
    "osc1Level": 95,
    "noiseLevel": 82,
    "filterCutoff": 55,
    "filterResonance": 32,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 28,
    "lfo1Wave": 2,
    "lfo1Rate": 12,
    "ampAttack": 42,
    "ampSustain": 100,
    "ampRelease": 100,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 35
  },
  {
    "name": "Rain",
    "osc1Wave": 6,
    "osc1Level": 88,
    "noiseLevel": 88,
    "filterCutoff": 70,
    "filterResonance": 30,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 32,
    "lfo1Wave": 2,
    "lfo1Rate": 30,
    "ampAttack": 22,
    "ampSustain": 100,
    "ampRelease": 82,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 35
  },
  {
    "name": "Static Hiss",
    "osc1Wave": 6,
    "osc1Level": 80,
    "noiseLevel": 95,
    "filterCutoff": 80,
    "filterResonance": 18,
    "ampAttack": 17,
    "ampSustain": 100,
    "ampRelease": 78,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Breath",
    "osc1Wave": 3,
    "osc1Level": 72,
    "noiseLevel": 75,
    "filterCutoff": 60,
    "filterResonance": 25,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 24,
    "lfo1Wave": 2,
    "lfo1Rate": 10,
    "ampAttack": 38,
    "ampSustain": 100,
    "ampRelease": 92,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 35
  },
  {
    "name": "Hum",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 85,
    "osc2Level": 82,
    "filterCutoff": 48,
    "filterResonance": 22,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 16,
    "lfo1Wave": 2,
    "lfo1Rate": 7,
    "ampAttack": 52,
    "ampSustain": 100,
    "ampRelease": 100,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 28
  }
];

module.exports = patches;
