// microKORG S patch library — 256 patches
// RESTRUCTURED: 128 Thick Basses + 32 Keys + 32 Pads + 64 FX
// NO global FX by default - clean patches, enable FX manually on hardware

const MC  = (n) => ({ vp2Src:6, vp2Dst:4, vp2Int:n });  // Mod→Cutoff
const MP  = (n) => ({ vp2Src:6, vp2Dst:0, vp2Int:n });  // Mod→Pitch
const MO2 = (n) => ({ vp2Src:6, vp2Dst:1, vp2Int:n });  // Mod→OSC2Pitch
const MC1 = (n) => ({ vp2Src:6, vp2Dst:2, vp2Int:n });  // Mod→Ctrl1
const ML  = (n) => ({ vp2Src:6, vp2Dst:7, vp2Int:n });  // Mod→LFO2Freq
const MA  = (n) => ({ vp2Src:6, vp2Dst:5, vp2Int:n });  // Mod→AMP

const patches = [
  {
    "name": "Deep Sine",
    "osc1Wave": 3,
    "osc1Level": 115,
    "filterCutoff": 38,
    "filterResonance": 5,
    "filterEgInt": 20,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 15,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 32
  },
  {
    "name": "Fat Sine",
    "osc1Wave": 3,
    "osc1Level": 115,
    "filterCutoff": 41,
    "filterResonance": 9,
    "filterEgInt": 25,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 20,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 34
  },
  {
    "name": "Warm Sub",
    "osc1Wave": 3,
    "osc1Level": 115,
    "filterCutoff": 44,
    "filterResonance": 13,
    "filterEgInt": 30,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 25,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 36
  },
  {
    "name": "Mellow",
    "osc1Wave": 3,
    "osc1Level": 115,
    "filterCutoff": 47,
    "filterResonance": 5,
    "filterEgInt": 35,
    "filterAttack": 0,
    "filterDecay": 25,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 15,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 38
  },
  {
    "name": "Dub Sine",
    "osc1Wave": 3,
    "osc1Level": 115,
    "filterCutoff": 38,
    "filterResonance": 9,
    "filterEgInt": 20,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 20,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 32
  },
  {
    "name": "Rolling",
    "osc1Wave": 3,
    "osc1Level": 115,
    "filterCutoff": 41,
    "filterResonance": 13,
    "filterEgInt": 25,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 25,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 34
  },
  {
    "name": "Pure Wump",
    "osc1Wave": 3,
    "osc1Level": 115,
    "filterCutoff": 44,
    "filterResonance": 5,
    "filterEgInt": 30,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 15,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 36
  },
  {
    "name": "Bloom",
    "osc1Wave": 3,
    "osc1Level": 115,
    "filterCutoff": 47,
    "filterResonance": 9,
    "filterEgInt": 35,
    "filterAttack": 0,
    "filterDecay": 25,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 20,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 38
  },
  {
    "name": "Deep Sine II",
    "osc1Wave": 3,
    "osc1Level": 115,
    "filterCutoff": 38,
    "filterResonance": 13,
    "filterEgInt": 20,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 25,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 32
  },
  {
    "name": "Fat Sine II",
    "osc1Wave": 3,
    "osc1Level": 115,
    "filterCutoff": 41,
    "filterResonance": 5,
    "filterEgInt": 25,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 15,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 34
  },
  {
    "name": "Warm Sub II",
    "osc1Wave": 3,
    "osc1Level": 115,
    "filterCutoff": 44,
    "filterResonance": 9,
    "filterEgInt": 30,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 20,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 36
  },
  {
    "name": "Mellow II",
    "osc1Wave": 3,
    "osc1Level": 115,
    "filterCutoff": 47,
    "filterResonance": 13,
    "filterEgInt": 35,
    "filterAttack": 0,
    "filterDecay": 25,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 25,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 38
  },
  {
    "name": "Dub Sine II",
    "osc1Wave": 3,
    "osc1Level": 115,
    "filterCutoff": 38,
    "filterResonance": 5,
    "filterEgInt": 20,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 15,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 32
  },
  {
    "name": "Rolling II",
    "osc1Wave": 3,
    "osc1Level": 115,
    "filterCutoff": 41,
    "filterResonance": 9,
    "filterEgInt": 25,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 20,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 34
  },
  {
    "name": "Pure Wump II",
    "osc1Wave": 3,
    "osc1Level": 115,
    "filterCutoff": 44,
    "filterResonance": 13,
    "filterEgInt": 30,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 25,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 36
  },
  {
    "name": "Bloom II",
    "osc1Wave": 3,
    "osc1Level": 115,
    "filterCutoff": 47,
    "filterResonance": 5,
    "filterEgInt": 35,
    "filterAttack": 0,
    "filterDecay": 25,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 15,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 38
  },
  {
    "name": "Saw Dub",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 50,
    "filterResonance": 12,
    "filterEgInt": 30,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 10,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 36
  },
  {
    "name": "Bright Saw",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 53,
    "filterResonance": 16,
    "filterEgInt": 35,
    "filterAttack": 0,
    "filterDecay": 25,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 14,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 38
  },
  {
    "name": "Thick Saw",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 56,
    "filterResonance": 20,
    "filterEgInt": 40,
    "filterAttack": 0,
    "filterDecay": 30,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 18,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 40
  },
  {
    "name": "Rich Wump",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 59,
    "filterResonance": 12,
    "filterEgInt": 45,
    "filterAttack": 0,
    "filterDecay": 35,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 10,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 42
  },
  {
    "name": "Cutting",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 50,
    "filterResonance": 16,
    "filterEgInt": 30,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 14,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 36
  },
  {
    "name": "Punchy Saw",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 53,
    "filterResonance": 20,
    "filterEgInt": 35,
    "filterAttack": 0,
    "filterDecay": 25,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 18,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 38
  },
  {
    "name": "Full Saw",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 56,
    "filterResonance": 12,
    "filterEgInt": 40,
    "filterAttack": 0,
    "filterDecay": 30,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 10,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 40
  },
  {
    "name": "Thunder",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 59,
    "filterResonance": 16,
    "filterEgInt": 45,
    "filterAttack": 0,
    "filterDecay": 35,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 14,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 42
  },
  {
    "name": "Saw Dub II",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 50,
    "filterResonance": 20,
    "filterEgInt": 30,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 18,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 36
  },
  {
    "name": "Bright Saw II",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 53,
    "filterResonance": 12,
    "filterEgInt": 35,
    "filterAttack": 0,
    "filterDecay": 25,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 10,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 38
  },
  {
    "name": "Thick Saw II",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 56,
    "filterResonance": 16,
    "filterEgInt": 40,
    "filterAttack": 0,
    "filterDecay": 30,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 14,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 40
  },
  {
    "name": "Rich Wump II",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 59,
    "filterResonance": 20,
    "filterEgInt": 45,
    "filterAttack": 0,
    "filterDecay": 35,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 18,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 42
  },
  {
    "name": "Cutting II",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 50,
    "filterResonance": 12,
    "filterEgInt": 30,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 10,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 36
  },
  {
    "name": "Punchy Saw II",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 53,
    "filterResonance": 16,
    "filterEgInt": 35,
    "filterAttack": 0,
    "filterDecay": 25,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 14,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 38
  },
  {
    "name": "Full Saw II",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 56,
    "filterResonance": 20,
    "filterEgInt": 40,
    "filterAttack": 0,
    "filterDecay": 30,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 18,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 40
  },
  {
    "name": "Thunder II",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 59,
    "filterResonance": 12,
    "filterEgInt": 45,
    "filterAttack": 0,
    "filterDecay": 35,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 10,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 42
  },
  {
    "name": "Square Wump",
    "osc1Wave": 1,
    "osc1Level": 115,
    "filterCutoff": 44,
    "filterResonance": 8,
    "filterEgInt": 25,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 33
  },
  {
    "name": "Pulse",
    "osc1Wave": 1,
    "osc1Level": 115,
    "filterCutoff": 47,
    "filterResonance": 12,
    "filterEgInt": 30,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 17,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Sync",
    "osc1Wave": 1,
    "osc1Level": 115,
    "filterCutoff": 50,
    "filterResonance": 16,
    "filterEgInt": 35,
    "filterAttack": 0,
    "filterDecay": 25,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 22,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 37
  },
  {
    "name": "Blocky",
    "osc1Wave": 1,
    "osc1Level": 115,
    "filterCutoff": 53,
    "filterResonance": 8,
    "filterEgInt": 40,
    "filterAttack": 0,
    "filterDecay": 30,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 39
  },
  {
    "name": "Pulse Dub",
    "osc1Wave": 1,
    "osc1Level": 115,
    "filterCutoff": 44,
    "filterResonance": 12,
    "filterEgInt": 25,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 17,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 33
  },
  {
    "name": "House",
    "osc1Wave": 1,
    "osc1Level": 115,
    "filterCutoff": 47,
    "filterResonance": 16,
    "filterEgInt": 30,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 22,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Synth",
    "osc1Wave": 1,
    "osc1Level": 115,
    "filterCutoff": 50,
    "filterResonance": 8,
    "filterEgInt": 35,
    "filterAttack": 0,
    "filterDecay": 25,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 37
  },
  {
    "name": "Roll",
    "osc1Wave": 1,
    "osc1Level": 115,
    "filterCutoff": 53,
    "filterResonance": 12,
    "filterEgInt": 40,
    "filterAttack": 0,
    "filterDecay": 30,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 17,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 39
  },
  {
    "name": "Square Wump II",
    "osc1Wave": 1,
    "osc1Level": 115,
    "filterCutoff": 44,
    "filterResonance": 16,
    "filterEgInt": 25,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 22,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 33
  },
  {
    "name": "Pulse II",
    "osc1Wave": 1,
    "osc1Level": 115,
    "filterCutoff": 47,
    "filterResonance": 8,
    "filterEgInt": 30,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Sync II",
    "osc1Wave": 1,
    "osc1Level": 115,
    "filterCutoff": 50,
    "filterResonance": 12,
    "filterEgInt": 35,
    "filterAttack": 0,
    "filterDecay": 25,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 17,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 37
  },
  {
    "name": "Blocky II",
    "osc1Wave": 1,
    "osc1Level": 115,
    "filterCutoff": 53,
    "filterResonance": 16,
    "filterEgInt": 40,
    "filterAttack": 0,
    "filterDecay": 30,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 22,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 39
  },
  {
    "name": "Pulse Dub II",
    "osc1Wave": 1,
    "osc1Level": 115,
    "filterCutoff": 44,
    "filterResonance": 8,
    "filterEgInt": 25,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 33
  },
  {
    "name": "House II",
    "osc1Wave": 1,
    "osc1Level": 115,
    "filterCutoff": 47,
    "filterResonance": 12,
    "filterEgInt": 30,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 17,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Synth II",
    "osc1Wave": 1,
    "osc1Level": 115,
    "filterCutoff": 50,
    "filterResonance": 16,
    "filterEgInt": 35,
    "filterAttack": 0,
    "filterDecay": 25,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 22,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 37
  },
  {
    "name": "Roll II",
    "osc1Wave": 1,
    "osc1Level": 115,
    "filterCutoff": 53,
    "filterResonance": 8,
    "filterEgInt": 40,
    "filterAttack": 0,
    "filterDecay": 30,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 39
  },
  {
    "name": "Smooth Tri",
    "osc1Wave": 2,
    "osc1Level": 115,
    "filterCutoff": 42,
    "filterResonance": 6,
    "filterEgInt": 18,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 18,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Creamy",
    "osc1Wave": 2,
    "osc1Level": 115,
    "filterCutoff": 45,
    "filterResonance": 9,
    "filterEgInt": 22,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 24,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 32
  },
  {
    "name": "Tri Dub",
    "osc1Wave": 2,
    "osc1Level": 115,
    "filterCutoff": 48,
    "filterResonance": 12,
    "filterEgInt": 26,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 30,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 34
  },
  {
    "name": "Silk",
    "osc1Wave": 2,
    "osc1Level": 115,
    "filterCutoff": 51,
    "filterResonance": 6,
    "filterEgInt": 30,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 18,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 36
  },
  {
    "name": "Cream",
    "osc1Wave": 2,
    "osc1Level": 115,
    "filterCutoff": 42,
    "filterResonance": 9,
    "filterEgInt": 18,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 24,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Smooth",
    "osc1Wave": 2,
    "osc1Level": 115,
    "filterCutoff": 45,
    "filterResonance": 12,
    "filterEgInt": 22,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 30,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 32
  },
  {
    "name": "Tri Wump",
    "osc1Wave": 2,
    "osc1Level": 115,
    "filterCutoff": 48,
    "filterResonance": 6,
    "filterEgInt": 26,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 18,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 34
  },
  {
    "name": "Velvet",
    "osc1Wave": 2,
    "osc1Level": 115,
    "filterCutoff": 51,
    "filterResonance": 9,
    "filterEgInt": 30,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 24,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 36
  },
  {
    "name": "Smooth Tri II",
    "osc1Wave": 2,
    "osc1Level": 115,
    "filterCutoff": 42,
    "filterResonance": 12,
    "filterEgInt": 18,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 30,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Creamy II",
    "osc1Wave": 2,
    "osc1Level": 115,
    "filterCutoff": 45,
    "filterResonance": 6,
    "filterEgInt": 22,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 18,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 32
  },
  {
    "name": "Tri Dub II",
    "osc1Wave": 2,
    "osc1Level": 115,
    "filterCutoff": 48,
    "filterResonance": 9,
    "filterEgInt": 26,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 24,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 34
  },
  {
    "name": "Silk II",
    "osc1Wave": 2,
    "osc1Level": 115,
    "filterCutoff": 51,
    "filterResonance": 12,
    "filterEgInt": 30,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 30,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 36
  },
  {
    "name": "Cream II",
    "osc1Wave": 2,
    "osc1Level": 115,
    "filterCutoff": 42,
    "filterResonance": 6,
    "filterEgInt": 18,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 18,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Smooth II",
    "osc1Wave": 2,
    "osc1Level": 115,
    "filterCutoff": 45,
    "filterResonance": 9,
    "filterEgInt": 22,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 24,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 32
  },
  {
    "name": "Tri Wump II",
    "osc1Wave": 2,
    "osc1Level": 115,
    "filterCutoff": 48,
    "filterResonance": 12,
    "filterEgInt": 26,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 30,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 34
  },
  {
    "name": "Velvet II",
    "osc1Wave": 2,
    "osc1Level": 115,
    "filterCutoff": 51,
    "filterResonance": 6,
    "filterEgInt": 30,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 18,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 36
  },
  {
    "name": "Layered",
    "osc1Wave": 3,
    "osc1Level": 115,
    "filterCutoff": 46,
    "filterResonance": 10,
    "filterEgInt": 32,
    "filterAttack": 0,
    "filterDecay": 22,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 16,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 38
  },
  {
    "name": "Dual",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 49,
    "filterResonance": 14,
    "filterEgInt": 37,
    "filterAttack": 0,
    "filterDecay": 27,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 21,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 40
  },
  {
    "name": "Thick",
    "osc1Wave": 2,
    "osc1Level": 115,
    "filterCutoff": 52,
    "filterResonance": 18,
    "filterEgInt": 42,
    "filterAttack": 0,
    "filterDecay": 32,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 26,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 42
  },
  {
    "name": "Harmonic",
    "osc1Wave": 3,
    "osc1Level": 115,
    "filterCutoff": 55,
    "filterResonance": 10,
    "filterEgInt": 47,
    "filterAttack": 0,
    "filterDecay": 37,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 16,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 44
  },
  {
    "name": "Double",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 46,
    "filterResonance": 14,
    "filterEgInt": 32,
    "filterAttack": 0,
    "filterDecay": 22,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 21,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 38
  },
  {
    "name": "Stacked",
    "osc1Wave": 3,
    "osc1Level": 115,
    "filterCutoff": 49,
    "filterResonance": 18,
    "filterEgInt": 37,
    "filterAttack": 0,
    "filterDecay": 27,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 26,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 40
  },
  {
    "name": "Full",
    "osc1Wave": 2,
    "osc1Level": 115,
    "filterCutoff": 52,
    "filterResonance": 10,
    "filterEgInt": 42,
    "filterAttack": 0,
    "filterDecay": 32,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 16,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 42
  },
  {
    "name": "Texture",
    "osc1Wave": 1,
    "osc1Level": 115,
    "filterCutoff": 55,
    "filterResonance": 14,
    "filterEgInt": 47,
    "filterAttack": 0,
    "filterDecay": 37,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 21,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 44
  },
  {
    "name": "Layered II",
    "osc1Wave": 3,
    "osc1Level": 115,
    "filterCutoff": 46,
    "filterResonance": 18,
    "filterEgInt": 32,
    "filterAttack": 0,
    "filterDecay": 22,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 26,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 38
  },
  {
    "name": "Dual II",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 49,
    "filterResonance": 10,
    "filterEgInt": 37,
    "filterAttack": 0,
    "filterDecay": 27,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 16,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 40
  },
  {
    "name": "Thick II",
    "osc1Wave": 2,
    "osc1Level": 115,
    "filterCutoff": 52,
    "filterResonance": 14,
    "filterEgInt": 42,
    "filterAttack": 0,
    "filterDecay": 32,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 21,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 42
  },
  {
    "name": "Harmonic II",
    "osc1Wave": 3,
    "osc1Level": 115,
    "filterCutoff": 55,
    "filterResonance": 18,
    "filterEgInt": 47,
    "filterAttack": 0,
    "filterDecay": 37,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 26,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 44
  },
  {
    "name": "Double II",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 46,
    "filterResonance": 10,
    "filterEgInt": 32,
    "filterAttack": 0,
    "filterDecay": 22,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 16,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 38
  },
  {
    "name": "Stacked II",
    "osc1Wave": 3,
    "osc1Level": 115,
    "filterCutoff": 49,
    "filterResonance": 14,
    "filterEgInt": 37,
    "filterAttack": 0,
    "filterDecay": 27,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 21,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 40
  },
  {
    "name": "Full II",
    "osc1Wave": 2,
    "osc1Level": 115,
    "filterCutoff": 52,
    "filterResonance": 18,
    "filterEgInt": 42,
    "filterAttack": 0,
    "filterDecay": 32,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 26,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 42
  },
  {
    "name": "Texture II",
    "osc1Wave": 1,
    "osc1Level": 115,
    "filterCutoff": 55,
    "filterResonance": 10,
    "filterEgInt": 47,
    "filterAttack": 0,
    "filterDecay": 37,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 16,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 44
  },
  {
    "name": "Funk Wump",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 32,
    "filterResonance": 16,
    "filterEgInt": 40,
    "filterAttack": 0,
    "filterDecay": 30,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 8,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 38
  },
  {
    "name": "Groove",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 36,
    "filterResonance": 19,
    "filterEgInt": 45,
    "filterAttack": 0,
    "filterDecay": 35,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 40
  },
  {
    "name": "House Funk",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 40,
    "filterResonance": 22,
    "filterEgInt": 50,
    "filterAttack": 0,
    "filterDecay": 40,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 16,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 42
  },
  {
    "name": "Filter",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 44,
    "filterResonance": 16,
    "filterEgInt": 55,
    "filterAttack": 0,
    "filterDecay": 45,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 8,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 44
  },
  {
    "name": "Wah",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 32,
    "filterResonance": 19,
    "filterEgInt": 40,
    "filterAttack": 0,
    "filterDecay": 30,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 38
  },
  {
    "name": "Envelope",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 36,
    "filterResonance": 22,
    "filterEgInt": 45,
    "filterAttack": 0,
    "filterDecay": 35,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 16,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 40
  },
  {
    "name": "Groove Wump",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 40,
    "filterResonance": 16,
    "filterEgInt": 50,
    "filterAttack": 0,
    "filterDecay": 40,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 8,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 42
  },
  {
    "name": "Funky",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 44,
    "filterResonance": 19,
    "filterEgInt": 55,
    "filterAttack": 0,
    "filterDecay": 45,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 44
  },
  {
    "name": "Funk Wump II",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 32,
    "filterResonance": 22,
    "filterEgInt": 40,
    "filterAttack": 0,
    "filterDecay": 30,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 16,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 38
  },
  {
    "name": "Groove II",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 36,
    "filterResonance": 16,
    "filterEgInt": 45,
    "filterAttack": 0,
    "filterDecay": 35,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 8,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 40
  },
  {
    "name": "House Funk II",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 40,
    "filterResonance": 19,
    "filterEgInt": 50,
    "filterAttack": 0,
    "filterDecay": 40,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 42
  },
  {
    "name": "Filter II",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 44,
    "filterResonance": 22,
    "filterEgInt": 55,
    "filterAttack": 0,
    "filterDecay": 45,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 16,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 44
  },
  {
    "name": "Wah II",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 32,
    "filterResonance": 16,
    "filterEgInt": 40,
    "filterAttack": 0,
    "filterDecay": 30,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 8,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 38
  },
  {
    "name": "Envelope II",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 36,
    "filterResonance": 19,
    "filterEgInt": 45,
    "filterAttack": 0,
    "filterDecay": 35,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 40
  },
  {
    "name": "Groove Wump II",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 40,
    "filterResonance": 22,
    "filterEgInt": 50,
    "filterAttack": 0,
    "filterDecay": 40,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 16,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 42
  },
  {
    "name": "Funky II",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 44,
    "filterResonance": 16,
    "filterEgInt": 55,
    "filterAttack": 0,
    "filterDecay": 45,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 8,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 44
  },
  {
    "name": "Acid Wump",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 40,
    "filterResonance": 18,
    "filterEgInt": 45,
    "filterAttack": 0,
    "filterDecay": 35,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 6,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 40
  },
  {
    "name": "Resonant",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 44,
    "filterResonance": 23,
    "filterEgInt": 51,
    "filterAttack": 0,
    "filterDecay": 41,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 9,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 42
  },
  {
    "name": "Sweep",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 48,
    "filterResonance": 28,
    "filterEgInt": 57,
    "filterAttack": 0,
    "filterDecay": 47,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 44
  },
  {
    "name": "TB",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 52,
    "filterResonance": 18,
    "filterEgInt": 63,
    "filterAttack": 0,
    "filterDecay": 53,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 6,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 46
  },
  {
    "name": "Sweep Bass",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 40,
    "filterResonance": 23,
    "filterEgInt": 45,
    "filterAttack": 0,
    "filterDecay": 35,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 9,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 40
  },
  {
    "name": "Peak",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 44,
    "filterResonance": 28,
    "filterEgInt": 51,
    "filterAttack": 0,
    "filterDecay": 41,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 42
  },
  {
    "name": "Acid House",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 48,
    "filterResonance": 18,
    "filterEgInt": 57,
    "filterAttack": 0,
    "filterDecay": 47,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 6,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 44
  },
  {
    "name": "Resonance",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 52,
    "filterResonance": 23,
    "filterEgInt": 63,
    "filterAttack": 0,
    "filterDecay": 53,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 9,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 46
  },
  {
    "name": "Acid Wump II",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 40,
    "filterResonance": 28,
    "filterEgInt": 45,
    "filterAttack": 0,
    "filterDecay": 35,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 40
  },
  {
    "name": "Resonant II",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 44,
    "filterResonance": 18,
    "filterEgInt": 51,
    "filterAttack": 0,
    "filterDecay": 41,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 6,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 42
  },
  {
    "name": "Sweep II",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 48,
    "filterResonance": 23,
    "filterEgInt": 57,
    "filterAttack": 0,
    "filterDecay": 47,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 9,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 44
  },
  {
    "name": "TB II",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 52,
    "filterResonance": 28,
    "filterEgInt": 63,
    "filterAttack": 0,
    "filterDecay": 53,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 46
  },
  {
    "name": "Sweep Bass II",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 40,
    "filterResonance": 18,
    "filterEgInt": 45,
    "filterAttack": 0,
    "filterDecay": 35,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 6,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 40
  },
  {
    "name": "Peak II",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 44,
    "filterResonance": 23,
    "filterEgInt": 51,
    "filterAttack": 0,
    "filterDecay": 41,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 9,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 42
  },
  {
    "name": "Acid House II",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 48,
    "filterResonance": 28,
    "filterEgInt": 57,
    "filterAttack": 0,
    "filterDecay": 47,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 12,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 44
  },
  {
    "name": "Resonance II",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 52,
    "filterResonance": 18,
    "filterEgInt": 63,
    "filterAttack": 0,
    "filterDecay": 53,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 6,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 46
  },
  {
    "name": "Hybrid",
    "osc1Wave": 3,
    "osc1Level": 115,
    "filterCutoff": 44,
    "filterResonance": 8,
    "filterEgInt": 26,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 20,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 34
  },
  {
    "name": "Warm Blend",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 47,
    "filterResonance": 12,
    "filterEgInt": 31,
    "filterAttack": 0,
    "filterDecay": 21,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 25,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 36
  },
  {
    "name": "Soft",
    "osc1Wave": 2,
    "osc1Level": 115,
    "filterCutoff": 50,
    "filterResonance": 16,
    "filterEgInt": 36,
    "filterAttack": 0,
    "filterDecay": 26,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 30,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 38
  },
  {
    "name": "Deep Ambient",
    "osc1Wave": 1,
    "osc1Level": 115,
    "filterCutoff": 53,
    "filterResonance": 8,
    "filterEgInt": 41,
    "filterAttack": 0,
    "filterDecay": 31,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 20,
    "vp2Src": 6,
    "vp2Dst": 1,
    "vp2Int": 40
  },
  {
    "name": "Clean",
    "osc1Wave": 3,
    "osc1Level": 115,
    "filterCutoff": 44,
    "filterResonance": 12,
    "filterEgInt": 26,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 25,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 34
  },
  {
    "name": "Ultra",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 47,
    "filterResonance": 16,
    "filterEgInt": 31,
    "filterAttack": 0,
    "filterDecay": 21,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 30,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 36
  },
  {
    "name": "Vintage",
    "osc1Wave": 2,
    "osc1Level": 115,
    "filterCutoff": 50,
    "filterResonance": 8,
    "filterEgInt": 36,
    "filterAttack": 0,
    "filterDecay": 26,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 20,
    "vp2Src": 6,
    "vp2Dst": 1,
    "vp2Int": 38
  },
  {
    "name": "Classic",
    "osc1Wave": 1,
    "osc1Level": 115,
    "filterCutoff": 53,
    "filterResonance": 12,
    "filterEgInt": 41,
    "filterAttack": 0,
    "filterDecay": 31,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 25,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 40
  },
  {
    "name": "Hybrid II",
    "osc1Wave": 3,
    "osc1Level": 115,
    "filterCutoff": 44,
    "filterResonance": 16,
    "filterEgInt": 26,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 30,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 34
  },
  {
    "name": "Warm Blend II",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 47,
    "filterResonance": 8,
    "filterEgInt": 31,
    "filterAttack": 0,
    "filterDecay": 21,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 20,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 36
  },
  {
    "name": "Soft II",
    "osc1Wave": 2,
    "osc1Level": 115,
    "filterCutoff": 50,
    "filterResonance": 12,
    "filterEgInt": 36,
    "filterAttack": 0,
    "filterDecay": 26,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 25,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 38
  },
  {
    "name": "Deep Ambient II",
    "osc1Wave": 1,
    "osc1Level": 115,
    "filterCutoff": 53,
    "filterResonance": 16,
    "filterEgInt": 41,
    "filterAttack": 0,
    "filterDecay": 31,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 30,
    "vp2Src": 6,
    "vp2Dst": 1,
    "vp2Int": 40
  },
  {
    "name": "Clean II",
    "osc1Wave": 3,
    "osc1Level": 115,
    "filterCutoff": 44,
    "filterResonance": 8,
    "filterEgInt": 26,
    "filterAttack": 0,
    "filterDecay": 20,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 20,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 34
  },
  {
    "name": "Ultra II",
    "osc1Wave": 0,
    "osc1Level": 115,
    "filterCutoff": 47,
    "filterResonance": 12,
    "filterEgInt": 31,
    "filterAttack": 0,
    "filterDecay": 21,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 25,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 36
  },
  {
    "name": "Vintage II",
    "osc1Wave": 2,
    "osc1Level": 115,
    "filterCutoff": 50,
    "filterResonance": 16,
    "filterEgInt": 36,
    "filterAttack": 0,
    "filterDecay": 26,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 30,
    "vp2Src": 6,
    "vp2Dst": 1,
    "vp2Int": 38
  },
  {
    "name": "Classic II",
    "osc1Wave": 1,
    "osc1Level": 115,
    "filterCutoff": 53,
    "filterResonance": 8,
    "filterEgInt": 41,
    "filterAttack": 0,
    "filterDecay": 31,
    "filterSustain": 0,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 90,
    "ampRelease": 45,
    "transpose": -12,
    "vibratoIntensity": 20,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 40
  },
  {
    "name": "Crystal Plk",
    "osc1Wave": 3,
    "osc1Level": 108,
    "filterCutoff": 100,
    "filterResonance": 38,
    "filterEgInt": 42,
    "filterDecay": 25,
    "ampAttack": 0,
    "ampDecay": 40,
    "ampSustain": 0,
    "ampRelease": 28,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Synth Pluck",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 100,
    "osc2Level": 52,
    "filterCutoff": 98,
    "filterResonance": 42,
    "filterEgInt": 40,
    "filterDecay": 24,
    "ampAttack": 0,
    "ampDecay": 35,
    "ampSustain": 0,
    "ampRelease": 25,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Funky Clav",
    "osc1Wave": 1,
    "osc1Level": 110,
    "filterCutoff": 108,
    "filterResonance": 55,
    "filterEgInt": 45,
    "filterDecay": 18,
    "ampAttack": 0,
    "ampDecay": 28,
    "ampSustain": 40,
    "ampRelease": 20,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Metal Pluck",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc2Mod": 1,
    "osc1Level": 100,
    "osc2Level": 82,
    "filterCutoff": 95,
    "filterResonance": 45,
    "filterEgInt": 38,
    "filterDecay": 22,
    "ampAttack": 0,
    "ampDecay": 35,
    "ampSustain": 0,
    "ampRelease": 25,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Rhodes Warm",
    "osc1Wave": 5,
    "osc1Level": 105,
    "filterCutoff": 88,
    "filterResonance": 20,
    "ampAttack": 5,
    "ampDecay": 52,
    "ampSustain": 72,
    "ampRelease": 50,
    "vp1Src": 4,
    "vp1Dst": 5,
    "vp1Int": 35,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Vintage Keys",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 95,
    "osc2Level": 82,
    "filterCutoff": 85,
    "filterResonance": 28,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 15,
    "lfo1Wave": 2,
    "lfo1Rate": 28,
    "ampAttack": 7,
    "ampDecay": 46,
    "ampSustain": 80,
    "ampRelease": 54,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Jazzy Keys",
    "osc1Wave": 5,
    "osc1Level": 102,
    "filterCutoff": 85,
    "filterResonance": 25,
    "filterEgInt": 22,
    "filterDecay": 35,
    "ampAttack": 6,
    "ampDecay": 46,
    "ampSustain": 78,
    "ampRelease": 52,
    "vp1Src": 4,
    "vp1Dst": 5,
    "vp1Int": 30,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Warm Bell",
    "osc1Wave": 3,
    "osc1Level": 105,
    "filterCutoff": 92,
    "filterResonance": 24,
    "ampAttack": 3,
    "ampDecay": 62,
    "ampSustain": 0,
    "ampRelease": 58,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 20
  },
  {
    "name": "Bell Pure",
    "osc1Wave": 3,
    "osc2Wave": 0,
    "osc2Mod": 1,
    "osc1Level": 100,
    "osc2Level": 58,
    "filterCutoff": 102,
    "filterResonance": 28,
    "ampAttack": 0,
    "ampDecay": 68,
    "ampSustain": 0,
    "ampRelease": 58,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 20
  },
  {
    "name": "Vibraphone",
    "osc1Wave": 3,
    "osc1Level": 108,
    "filterCutoff": 102,
    "filterResonance": 20,
    "vp1Src": 2,
    "vp1Dst": 0,
    "vp1Int": 12,
    "lfo1Wave": 2,
    "lfo1Rate": 70,
    "ampAttack": 2,
    "ampDecay": 44,
    "ampSustain": 0,
    "ampRelease": 40,
    "vibratoIntensity": 42,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 18
  },
  {
    "name": "Soft Bell",
    "osc1Wave": 3,
    "osc1Level": 100,
    "filterCutoff": 96,
    "filterResonance": 20,
    "ampAttack": 2,
    "ampDecay": 72,
    "ampSustain": 0,
    "ampRelease": 68,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 20
  },
  {
    "name": "Ting",
    "osc1Wave": 3,
    "osc1Level": 108,
    "filterCutoff": 112,
    "filterResonance": 32,
    "filterEgInt": 28,
    "filterDecay": 15,
    "ampAttack": 0,
    "ampDecay": 18,
    "ampSustain": 0,
    "ampRelease": 18,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 15
  },
  {
    "name": "Hammond Full",
    "osc1Wave": 1,
    "osc2Wave": 1,
    "osc1Level": 105,
    "osc2Level": 75,
    "filterCutoff": 112,
    "filterResonance": 0,
    "ampAttack": 0,
    "ampSustain": 127,
    "ampRelease": 8,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 22
  },
  {
    "name": "Gospel Keys",
    "osc1Wave": 1,
    "osc2Wave": 2,
    "osc1Level": 102,
    "osc2Level": 72,
    "filterCutoff": 108,
    "filterResonance": 5,
    "ampAttack": 0,
    "ampSustain": 127,
    "ampRelease": 10,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Rock Organ",
    "osc1Wave": 1,
    "osc2Wave": 0,
    "osc1Level": 108,
    "osc2Level": 80,
    "filterCutoff": 115,
    "filterResonance": 0,
    "ampAttack": 0,
    "ampSustain": 127,
    "ampRelease": 8,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Rotary Slow",
    "osc1Wave": 1,
    "osc2Wave": 1,
    "osc1Level": 100,
    "osc2Level": 65,
    "filterCutoff": 105,
    "filterResonance": 5,
    "vp1Src": 2,
    "vp1Dst": 6,
    "vp1Int": 35,
    "lfo1Wave": 2,
    "lfo1Rate": 18,
    "ampAttack": 0,
    "ampSustain": 127,
    "ampRelease": 10,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 22
  },
  {
    "name": "Whistle",
    "osc1Wave": 3,
    "osc1Level": 110,
    "filterCutoff": 100,
    "filterResonance": 10,
    "vp1Src": 3,
    "vp1Dst": 0,
    "vp1Int": 22,
    "lfo2Wave": 2,
    "lfo2Rate": 70,
    "ampAttack": 8,
    "ampSustain": 100,
    "ampRelease": 45,
    "vibratoIntensity": 38,
    "vp2Src": 6,
    "vp2Dst": 0,
    "vp2Int": 28
  },
  {
    "name": "Slow Whistle",
    "osc1Wave": 3,
    "osc1Level": 108,
    "filterCutoff": 100,
    "filterResonance": 10,
    "vp1Src": 3,
    "vp1Dst": 0,
    "vp1Int": 18,
    "lfo2Wave": 2,
    "lfo2Rate": 70,
    "ampAttack": 10,
    "ampSustain": 100,
    "ampRelease": 50,
    "vibratoIntensity": 35,
    "vp2Src": 6,
    "vp2Dst": 0,
    "vp2Int": 22
  },
  {
    "name": "Velvet Lead",
    "osc1Wave": 3,
    "osc2Wave": 0,
    "osc1Level": 100,
    "osc2Level": 30,
    "filterCutoff": 92,
    "filterResonance": 22,
    "filterEgInt": 18,
    "filterDecay": 40,
    "vp1Src": 3,
    "vp1Dst": 0,
    "vp1Int": 15,
    "lfo2Wave": 2,
    "lfo2Rate": 70,
    "ampAttack": 6,
    "ampSustain": 100,
    "ampRelease": 48,
    "vibratoIntensity": 36,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 20
  },
  {
    "name": "Warm Sine",
    "osc1Wave": 3,
    "osc1Level": 108,
    "filterCutoff": 90,
    "filterResonance": 15,
    "ampAttack": 6,
    "ampSustain": 100,
    "ampRelease": 46,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 18
  },
  {
    "name": "Sync Lead",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc2Mod": 2,
    "osc1Level": 102,
    "osc2Level": 52,
    "filterCutoff": 88,
    "filterResonance": 68,
    "filterEgInt": 42,
    "filterDecay": 30,
    "ampAttack": 2,
    "ampDecay": 50,
    "ampSustain": 85,
    "ampRelease": 32,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "PWM Lead",
    "osc1Wave": 1,
    "osc1Level": 105,
    "filterCutoff": 90,
    "filterResonance": 35,
    "vp1Src": 2,
    "vp1Dst": 2,
    "vp1Int": 40,
    "lfo1Wave": 2,
    "lfo1Rate": 30,
    "ampAttack": 5,
    "ampSustain": 100,
    "ampRelease": 38,
    "vp2Src": 6,
    "vp2Dst": 2,
    "vp2Int": 35
  },
  {
    "name": "Buzz Lead",
    "osc1Wave": 0,
    "osc1Level": 105,
    "filterCutoff": 72,
    "filterResonance": 110,
    "filterEgInt": 44,
    "filterDecay": 35,
    "ampAttack": 2,
    "ampDecay": 52,
    "ampSustain": 85,
    "ampRelease": 32,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Screamer",
    "osc1Wave": 0,
    "osc1Level": 100,
    "filterCutoff": 70,
    "filterResonance": 118,
    "filterEgInt": 40,
    "filterDecay": 35,
    "ampAttack": 2,
    "ampDecay": 48,
    "ampSustain": 78,
    "ampRelease": 30,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Soul Lead",
    "osc1Wave": 3,
    "osc2Wave": 2,
    "osc1Level": 102,
    "osc2Level": 32,
    "filterCutoff": 94,
    "filterResonance": 20,
    "ampAttack": 7,
    "ampSustain": 100,
    "ampRelease": 50,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 22
  },
  {
    "name": "Funky Lead",
    "osc1Wave": 0,
    "osc1Level": 108,
    "filterCutoff": 42,
    "filterResonance": 75,
    "filterEgInt": 54,
    "filterAttack": 0,
    "filterDecay": 38,
    "filterSustain": 10,
    "ampAttack": 2,
    "ampSustain": 92,
    "ampRelease": 38,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 40
  },
  {
    "name": "Phaser Lead",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 95,
    "osc2Level": 88,
    "filterCutoff": 82,
    "filterResonance": 42,
    "vp1Src": 2,
    "vp1Dst": 6,
    "vp1Int": 40,
    "lfo1Wave": 2,
    "lfo1Rate": 18,
    "ampAttack": 4,
    "ampSustain": 100,
    "ampRelease": 42,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Squeal",
    "osc1Wave": 0,
    "osc1Level": 100,
    "filterCutoff": 68,
    "filterResonance": 115,
    "filterEgInt": 38,
    "filterDecay": 35,
    "ampAttack": 3,
    "ampDecay": 52,
    "ampSustain": 85,
    "ampRelease": 38,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Rhodes Brite",
    "osc1Wave": 5,
    "osc1Level": 108,
    "filterCutoff": 100,
    "filterResonance": 30,
    "filterEgInt": 28,
    "filterDecay": 30,
    "ampAttack": 3,
    "ampDecay": 46,
    "ampSustain": 68,
    "ampRelease": 46,
    "vp1Src": 4,
    "vp1Dst": 5,
    "vp1Int": 38,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 28
  },
  {
    "name": "Funk Keys",
    "osc1Wave": 5,
    "osc1Level": 105,
    "filterCutoff": 75,
    "filterResonance": 38,
    "filterEgInt": 32,
    "filterDecay": 28,
    "ampAttack": 4,
    "ampDecay": 50,
    "ampSustain": 70,
    "ampRelease": 44,
    "vp1Src": 4,
    "vp1Dst": 5,
    "vp1Int": 35,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Clavi Soft",
    "osc1Wave": 1,
    "osc1Level": 105,
    "filterCutoff": 92,
    "filterResonance": 40,
    "filterEgInt": 38,
    "filterDecay": 22,
    "ampAttack": 0,
    "ampDecay": 35,
    "ampSustain": 55,
    "ampRelease": 25,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 28
  },
  {
    "name": "Night Keys",
    "osc1Wave": 5,
    "osc1Level": 102,
    "filterCutoff": 72,
    "filterResonance": 22,
    "ampAttack": 7,
    "ampDecay": 56,
    "ampSustain": 70,
    "ampRelease": 56,
    "vp1Src": 4,
    "vp1Dst": 5,
    "vp1Int": 30,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Warm Pad",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 92,
    "osc2Level": 85,
    "filterCutoff": 72,
    "filterResonance": 18,
    "ampAttack": 25,
    "ampSustain": 100,
    "ampRelease": 82,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Velvet Pad",
    "osc1Wave": 2,
    "osc1Level": 90,
    "filterCutoff": 68,
    "filterResonance": 15,
    "ampAttack": 28,
    "ampSustain": 100,
    "ampRelease": 88,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Cloud",
    "osc1Wave": 2,
    "osc2Wave": 0,
    "osc1Level": 88,
    "osc2Level": 82,
    "filterCutoff": 65,
    "filterResonance": 14,
    "ampAttack": 35,
    "ampSustain": 100,
    "ampRelease": 92,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Juno Pad",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 90,
    "osc2Level": 84,
    "filterCutoff": 78,
    "filterResonance": 24,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 15,
    "lfo1Wave": 2,
    "lfo1Rate": 22,
    "ampAttack": 22,
    "ampSustain": 100,
    "ampRelease": 82,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Breathing",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 90,
    "osc2Level": 82,
    "filterCutoff": 72,
    "filterResonance": 20,
    "vp1Src": 2,
    "vp1Dst": 5,
    "vp1Int": 35,
    "lfo1Wave": 2,
    "lfo1Rate": 14,
    "ampAttack": 22,
    "ampSustain": 100,
    "ampRelease": 80,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Morphing Pad",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 82,
    "filterCutoff": 58,
    "filterResonance": 28,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 30,
    "lfo1Wave": 2,
    "lfo1Rate": 12,
    "ampAttack": 24,
    "ampSustain": 100,
    "ampRelease": 84,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 38
  },
  {
    "name": "Tidal",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 84,
    "filterCutoff": 60,
    "filterResonance": 22,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 28,
    "lfo1Wave": 2,
    "lfo1Rate": 9,
    "ampAttack": 30,
    "ampSustain": 100,
    "ampRelease": 92,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Waves",
    "osc1Wave": 2,
    "osc1Level": 90,
    "filterCutoff": 68,
    "filterResonance": 25,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 30,
    "lfo1Wave": 2,
    "lfo1Rate": 16,
    "ampAttack": 28,
    "ampSustain": 100,
    "ampRelease": 88,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Strings",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 90,
    "osc2Level": 86,
    "filterCutoff": 80,
    "filterResonance": 20,
    "ampAttack": 20,
    "ampSustain": 100,
    "ampRelease": 78,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Cello",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 90,
    "osc2Level": 72,
    "filterCutoff": 70,
    "filterResonance": 22,
    "ampAttack": 25,
    "ampSustain": 100,
    "ampRelease": 80,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Violin Hi",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 88,
    "osc2Level": 86,
    "filterCutoff": 85,
    "filterResonance": 20,
    "ampAttack": 25,
    "ampSustain": 100,
    "ampRelease": 72,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Slow Bow",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 88,
    "osc2Level": 84,
    "filterCutoff": 72,
    "filterResonance": 20,
    "ampAttack": 38,
    "ampSustain": 100,
    "ampRelease": 90,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Deep Space",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 85,
    "osc2Level": 84,
    "filterCutoff": 58,
    "filterResonance": 20,
    "ampAttack": 38,
    "ampSustain": 100,
    "ampRelease": 100,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Nebula",
    "osc1Wave": 2,
    "osc1Level": 82,
    "noiseLevel": 28,
    "filterCutoff": 56,
    "filterResonance": 22,
    "ampAttack": 40,
    "ampSustain": 100,
    "ampRelease": 100,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Void",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 80,
    "osc2Level": 82,
    "filterCutoff": 50,
    "filterResonance": 18,
    "ampAttack": 45,
    "ampSustain": 100,
    "ampRelease": 100,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Horizon",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 85,
    "osc2Level": 82,
    "filterCutoff": 64,
    "filterResonance": 18,
    "ampAttack": 28,
    "ampSustain": 100,
    "ampRelease": 94,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Twilight",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 86,
    "filterCutoff": 68,
    "filterResonance": 16,
    "ampAttack": 26,
    "ampSustain": 100,
    "ampRelease": 90,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Dawn",
    "osc1Wave": 2,
    "osc2Wave": 0,
    "osc1Level": 88,
    "osc2Level": 80,
    "filterCutoff": 74,
    "filterResonance": 18,
    "ampAttack": 22,
    "ampSustain": 100,
    "ampRelease": 84,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Evening",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 84,
    "filterCutoff": 68,
    "filterResonance": 16,
    "ampAttack": 27,
    "ampSustain": 100,
    "ampRelease": 90,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "First Light",
    "osc1Wave": 3,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 80,
    "filterCutoff": 72,
    "filterResonance": 16,
    "ampAttack": 24,
    "ampSustain": 100,
    "ampRelease": 84,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Resonant Pad",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 80,
    "filterCutoff": 56,
    "filterResonance": 72,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 30,
    "lfo1Wave": 2,
    "lfo1Rate": 70,
    "ampAttack": 24,
    "ampSustain": 100,
    "ampRelease": 84,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 40
  },
  {
    "name": "Filtered Pad",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 80,
    "filterCutoff": 50,
    "filterResonance": 78,
    "filterEgInt": 45,
    "filterAttack": 18,
    "filterDecay": 72,
    "ampAttack": 24,
    "ampSustain": 100,
    "ampRelease": 84,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 40
  },
  {
    "name": "Bloom",
    "osc1Wave": 2,
    "osc1Level": 88,
    "filterCutoff": 46,
    "filterResonance": 75,
    "filterEgInt": 58,
    "filterAttack": 22,
    "filterDecay": 92,
    "ampAttack": 28,
    "ampSustain": 100,
    "ampRelease": 92,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 42
  },
  {
    "name": "Crystal Pad",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 82,
    "filterCutoff": 82,
    "filterResonance": 62,
    "filterEgInt": 30,
    "filterDecay": 52,
    "ampAttack": 20,
    "ampSustain": 100,
    "ampRelease": 80,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Wide Pad",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 90,
    "osc2Level": 88,
    "filterCutoff": 75,
    "filterResonance": 20,
    "ampAttack": 24,
    "ampSustain": 100,
    "ampRelease": 84,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Chorus Pad",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 84,
    "filterCutoff": 76,
    "filterResonance": 20,
    "ampAttack": 24,
    "ampSustain": 100,
    "ampRelease": 84,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Floating",
    "osc1Wave": 3,
    "osc2Wave": 2,
    "osc1Level": 85,
    "osc2Level": 84,
    "filterCutoff": 70,
    "filterResonance": 16,
    "ampAttack": 30,
    "ampSustain": 100,
    "ampRelease": 90,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Haze",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 85,
    "osc2Level": 82,
    "filterCutoff": 68,
    "filterResonance": 18,
    "ampAttack": 30,
    "ampSustain": 100,
    "ampRelease": 90,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Dub Pad",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 90,
    "osc2Level": 78,
    "filterCutoff": 70,
    "filterResonance": 22,
    "ampAttack": 25,
    "ampSustain": 100,
    "ampRelease": 78,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Dub Chord",
    "osc1Wave": 0,
    "osc2Wave": 1,
    "osc1Level": 88,
    "osc2Level": 74,
    "filterCutoff": 72,
    "filterResonance": 24,
    "ampAttack": 25,
    "ampDecay": 52,
    "ampSustain": 74,
    "ampRelease": 67,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Reverb Pad",
    "osc1Wave": 3,
    "osc2Wave": 2,
    "osc1Level": 85,
    "osc2Level": 80,
    "filterCutoff": 68,
    "filterResonance": 18,
    "ampAttack": 24,
    "ampSustain": 100,
    "ampRelease": 92,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Echo Drift",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 85,
    "osc2Level": 82,
    "filterCutoff": 65,
    "filterResonance": 20,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 20,
    "lfo1Wave": 2,
    "lfo1Rate": 8,
    "ampAttack": 27,
    "ampSustain": 100,
    "ampRelease": 90,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Dub Echo",
    "osc1Wave": 0,
    "osc1Level": 105,
    "filterCutoff": 70,
    "filterResonance": 30,
    "ampAttack": 3,
    "ampDecay": 55,
    "ampSustain": 62,
    "ampRelease": 58,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Skank Echo",
    "osc1Wave": 0,
    "osc2Wave": 1,
    "osc1Level": 100,
    "osc2Level": 58,
    "filterCutoff": 85,
    "filterResonance": 38,
    "filterEgInt": 32,
    "filterDecay": 25,
    "ampAttack": 1,
    "ampDecay": 30,
    "ampSustain": 0,
    "ampRelease": 25,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Dub Note",
    "osc1Wave": 2,
    "osc1Level": 102,
    "filterCutoff": 74,
    "filterResonance": 32,
    "ampAttack": 3,
    "ampDecay": 45,
    "ampSustain": 52,
    "ampRelease": 52,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Deep Dub",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 100,
    "osc2Level": 60,
    "filterCutoff": 62,
    "filterResonance": 30,
    "ampAttack": 5,
    "ampSustain": 82,
    "ampRelease": 67,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Delay Fade",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 95,
    "osc2Level": 78,
    "filterCutoff": 70,
    "filterResonance": 24,
    "ampAttack": 5,
    "ampDecay": 62,
    "ampSustain": 42,
    "ampRelease": 67,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Dub Stab",
    "osc1Wave": 0,
    "osc2Wave": 1,
    "osc1Level": 102,
    "osc2Level": 62,
    "filterCutoff": 88,
    "filterResonance": 45,
    "filterEgInt": 38,
    "filterDecay": 20,
    "ampAttack": 0,
    "ampDecay": 28,
    "ampSustain": 0,
    "ampRelease": 22,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Echo Lead",
    "osc1Wave": 0,
    "osc1Level": 105,
    "filterCutoff": 88,
    "filterResonance": 35,
    "ampAttack": 3,
    "ampSustain": 92,
    "ampRelease": 44,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Dub Organ",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 95,
    "osc2Level": 68,
    "filterCutoff": 80,
    "filterResonance": 24,
    "ampAttack": 5,
    "ampSustain": 100,
    "ampRelease": 52,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Bubbling",
    "osc1Wave": 0,
    "osc1Level": 108,
    "filterCutoff": 50,
    "filterResonance": 100,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 52,
    "lfo1Wave": 2,
    "lfo1Rate": 72,
    "ampAttack": 2,
    "ampSustain": 100,
    "ampRelease": 40,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 45
  },
  {
    "name": "Gurgle",
    "osc1Wave": 0,
    "osc1Level": 108,
    "filterCutoff": 46,
    "filterResonance": 108,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 56,
    "lfo1Wave": 2,
    "lfo1Rate": 62,
    "ampAttack": 2,
    "ampSustain": 100,
    "ampRelease": 38,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 45
  },
  {
    "name": "Percolate",
    "osc1Wave": 0,
    "osc1Level": 105,
    "filterCutoff": 53,
    "filterResonance": 98,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 48,
    "lfo1Wave": 2,
    "lfo1Rate": 75,
    "ampAttack": 1,
    "ampSustain": 100,
    "ampRelease": 35,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 45
  },
  {
    "name": "Fizz",
    "osc1Wave": 1,
    "osc1Level": 100,
    "filterCutoff": 60,
    "filterResonance": 92,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 45,
    "lfo1Wave": 2,
    "lfo1Rate": 82,
    "ampAttack": 1,
    "ampSustain": 100,
    "ampRelease": 32,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 45
  },
  {
    "name": "Drip",
    "osc1Wave": 3,
    "osc1Level": 100,
    "filterCutoff": 48,
    "filterResonance": 102,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 52,
    "lfo1Wave": 2,
    "lfo1Rate": 50,
    "ampAttack": 2,
    "ampSustain": 100,
    "ampRelease": 45,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 42
  },
  {
    "name": "Boil",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 105,
    "osc2Level": 78,
    "filterCutoff": 48,
    "filterResonance": 105,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 55,
    "lfo1Wave": 3,
    "lfo1Rate": 72,
    "ampAttack": 1,
    "ampSustain": 100,
    "ampRelease": 35,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 45
  },
  {
    "name": "Brook",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 95,
    "osc2Level": 78,
    "filterCutoff": 56,
    "filterResonance": 80,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 44,
    "lfo1Wave": 2,
    "lfo1Rate": 58,
    "ampAttack": 3,
    "ampSustain": 100,
    "ampRelease": 45,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 42
  },
  {
    "name": "Ocean",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 90,
    "osc2Level": 82,
    "filterCutoff": 54,
    "filterResonance": 68,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 38,
    "lfo1Wave": 2,
    "lfo1Rate": 45,
    "ampAttack": 8,
    "ampSustain": 100,
    "ampRelease": 62,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 42
  },
  {
    "name": "Psy Chorus",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 92,
    "osc2Level": 88,
    "filterCutoff": 78,
    "filterResonance": 32,
    "ampAttack": 5,
    "ampSustain": 100,
    "ampRelease": 50,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 35
  },
  {
    "name": "Spiral FX",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 90,
    "osc2Level": 82,
    "filterCutoff": 62,
    "filterResonance": 78,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 42,
    "lfo1Wave": 2,
    "lfo1Rate": 52,
    "ampAttack": 4,
    "ampSustain": 100,
    "ampRelease": 48,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 42
  },
  {
    "name": "Trippy",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 90,
    "osc2Level": 82,
    "filterCutoff": 60,
    "filterResonance": 82,
    "vp1Src": 2,
    "vp1Dst": 0,
    "vp1Int": 15,
    "lfo1Wave": 2,
    "lfo1Rate": 75,
    "ampAttack": 5,
    "ampSustain": 100,
    "ampRelease": 50,
    "vibratoIntensity": 42,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 40
  },
  {
    "name": "Shpongle",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 86,
    "filterCutoff": 65,
    "filterResonance": 60,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 30,
    "lfo1Wave": 2,
    "lfo1Rate": 20,
    "ampAttack": 8,
    "ampSustain": 100,
    "ampRelease": 58,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 38
  },
  {
    "name": "Wavering",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 90,
    "osc2Level": 82,
    "filterCutoff": 70,
    "filterResonance": 32,
    "vp1Src": 2,
    "vp1Dst": 0,
    "vp1Int": 20,
    "lfo1Wave": 2,
    "lfo1Rate": 70,
    "ampAttack": 6,
    "ampSustain": 100,
    "ampRelease": 52,
    "vibratoIntensity": 44,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 30
  },
  {
    "name": "Drift",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 88,
    "osc2Level": 84,
    "filterCutoff": 65,
    "filterResonance": 24,
    "vp1Src": 2,
    "vp1Dst": 0,
    "vp1Int": 10,
    "lfo1Wave": 2,
    "lfo1Rate": 70,
    "ampAttack": 12,
    "ampSustain": 100,
    "ampRelease": 65,
    "vibratoIntensity": 38,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 30
  },
  {
    "name": "Floating FX",
    "osc1Wave": 3,
    "osc2Wave": 2,
    "osc1Level": 85,
    "osc2Level": 80,
    "filterCutoff": 68,
    "filterResonance": 20,
    "ampAttack": 20,
    "ampSustain": 100,
    "ampRelease": 82,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Vortex",
    "osc1Wave": 0,
    "osc1Level": 105,
    "filterCutoff": 52,
    "filterResonance": 95,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 52,
    "lfo1Wave": 2,
    "lfo1Rate": 78,
    "ampAttack": 2,
    "ampSustain": 100,
    "ampRelease": 38,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 45
  },
  {
    "name": "Arp Note",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 102,
    "osc2Level": 56,
    "filterCutoff": 92,
    "filterResonance": 35,
    "filterEgInt": 30,
    "filterDecay": 22,
    "ampAttack": 1,
    "ampDecay": 28,
    "ampSustain": 52,
    "ampRelease": 22,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Stab Arp",
    "osc1Wave": 0,
    "osc1Level": 108,
    "filterCutoff": 98,
    "filterResonance": 45,
    "filterEgInt": 38,
    "filterDecay": 18,
    "ampAttack": 0,
    "ampDecay": 22,
    "ampSustain": 0,
    "ampRelease": 18,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Bright Arp",
    "osc1Wave": 0,
    "osc2Wave": 1,
    "osc1Level": 102,
    "osc2Level": 46,
    "filterCutoff": 104,
    "filterResonance": 40,
    "filterEgInt": 32,
    "filterDecay": 18,
    "ampAttack": 0,
    "ampDecay": 25,
    "ampSustain": 20,
    "ampRelease": 20,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Dark Arp",
    "osc1Wave": 0,
    "osc1Level": 105,
    "filterCutoff": 70,
    "filterResonance": 50,
    "filterEgInt": 40,
    "filterDecay": 25,
    "ampAttack": 1,
    "ampDecay": 30,
    "ampSustain": 32,
    "ampRelease": 25,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Acid Arp",
    "osc1Wave": 0,
    "osc1Level": 108,
    "filterCutoff": 52,
    "filterResonance": 92,
    "filterEgInt": 52,
    "filterDecay": 22,
    "ampAttack": 0,
    "ampDecay": 25,
    "ampSustain": 40,
    "ampRelease": 20,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Bell Arp",
    "osc1Wave": 3,
    "osc2Wave": 0,
    "osc2Mod": 1,
    "osc1Level": 100,
    "osc2Level": 60,
    "filterCutoff": 100,
    "filterResonance": 30,
    "ampAttack": 0,
    "ampDecay": 45,
    "ampSustain": 0,
    "ampRelease": 35,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 20
  },
  {
    "name": "Gate Arp",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 100,
    "osc2Level": 60,
    "filterCutoff": 88,
    "filterResonance": 38,
    "vp1Src": 2,
    "vp1Dst": 5,
    "vp1Int": 45,
    "lfo1Wave": 1,
    "lfo1Rate": 60,
    "ampAttack": 1,
    "ampSustain": 100,
    "ampRelease": 20,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 35
  },
  {
    "name": "Bass Arp",
    "osc1Wave": 0,
    "osc1Level": 110,
    "filterCutoff": 76,
    "filterResonance": 45,
    "filterEgInt": 40,
    "filterDecay": 22,
    "ampAttack": 0,
    "ampDecay": 32,
    "ampSustain": 30,
    "ampRelease": 22,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Classic Stab",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 98,
    "osc2Level": 90,
    "filterCutoff": 96,
    "filterResonance": 45,
    "filterEgInt": 35,
    "filterDecay": 18,
    "ampAttack": 0,
    "ampDecay": 25,
    "ampSustain": 0,
    "ampRelease": 18,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "House Stab",
    "osc1Wave": 0,
    "osc2Wave": 1,
    "osc1Level": 95,
    "osc2Level": 80,
    "filterCutoff": 90,
    "filterResonance": 38,
    "filterEgInt": 30,
    "filterDecay": 20,
    "ampAttack": 0,
    "ampDecay": 28,
    "ampSustain": 0,
    "ampRelease": 20,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Psy Stab",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc2Mod": 2,
    "osc1Level": 100,
    "osc2Level": 58,
    "filterCutoff": 92,
    "filterResonance": 65,
    "filterEgInt": 40,
    "filterDecay": 18,
    "ampAttack": 0,
    "ampDecay": 22,
    "ampSustain": 0,
    "ampRelease": 16,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Techno Hit",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 102,
    "osc2Level": 88,
    "filterCutoff": 100,
    "filterResonance": 52,
    "filterEgInt": 35,
    "filterDecay": 16,
    "ampAttack": 0,
    "ampDecay": 22,
    "ampSustain": 0,
    "ampRelease": 15,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Bell Hit",
    "osc1Wave": 3,
    "osc2Wave": 0,
    "osc2Mod": 1,
    "osc1Level": 100,
    "osc2Level": 74,
    "filterCutoff": 100,
    "filterResonance": 35,
    "ampAttack": 0,
    "ampDecay": 40,
    "ampSustain": 0,
    "ampRelease": 32,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 20
  },
  {
    "name": "Chord Hit",
    "osc1Wave": 0,
    "osc2Wave": 1,
    "osc1Level": 95,
    "osc2Level": 82,
    "filterCutoff": 88,
    "filterResonance": 30,
    "filterEgInt": 28,
    "filterDecay": 20,
    "ampAttack": 2,
    "ampDecay": 32,
    "ampSustain": 0,
    "ampRelease": 22,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Brass Hit",
    "osc1Wave": 0,
    "osc1Level": 110,
    "filterCutoff": 100,
    "filterResonance": 40,
    "filterEgInt": 38,
    "filterDecay": 18,
    "ampAttack": 2,
    "ampDecay": 35,
    "ampSustain": 20,
    "ampRelease": 22,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Pluck Hit",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 105,
    "osc2Level": 54,
    "filterCutoff": 102,
    "filterResonance": 48,
    "filterEgInt": 40,
    "filterDecay": 18,
    "ampAttack": 0,
    "ampDecay": 25,
    "ampSustain": 0,
    "ampRelease": 18,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 25
  },
  {
    "name": "Filter Rise",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 105,
    "osc2Level": 82,
    "filterCutoff": 22,
    "filterResonance": 68,
    "filterEgInt": 62,
    "filterAttack": 82,
    "filterDecay": 100,
    "ampAttack": 0,
    "ampSustain": 100,
    "ampRelease": 35,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 45
  },
  {
    "name": "Pitch Rise",
    "osc1Wave": 0,
    "osc1Level": 108,
    "filterCutoff": 88,
    "filterResonance": 35,
    "vp1Src": 1,
    "vp1Dst": 0,
    "vp1Int": 55,
    "ampAttack": 0,
    "ampDecay": 70,
    "ampSustain": 72,
    "ampRelease": 42,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 40
  },
  {
    "name": "Noise Rise",
    "osc1Wave": 6,
    "osc1Level": 100,
    "noiseLevel": 90,
    "filterCutoff": 20,
    "filterResonance": 60,
    "filterEgInt": 62,
    "filterAttack": 92,
    "filterDecay": 100,
    "ampAttack": 10,
    "ampSustain": 100,
    "ampRelease": 42,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 45
  },
  {
    "name": "Sub Drop",
    "osc1Wave": 3,
    "osc1Level": 115,
    "filterCutoff": 58,
    "filterResonance": 18,
    "vp1Src": 1,
    "vp1Dst": 0,
    "vp1Int": -38,
    "ampAttack": 0,
    "ampDecay": 92,
    "ampSustain": 52,
    "ampRelease": 62,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Slow Rise",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 98,
    "osc2Level": 82,
    "filterCutoff": 18,
    "filterResonance": 58,
    "filterEgInt": 60,
    "filterAttack": 100,
    "filterDecay": 100,
    "ampAttack": 15,
    "ampSustain": 100,
    "ampRelease": 52,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 45
  },
  {
    "name": "Rev Env",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc1Level": 100,
    "osc2Level": 80,
    "filterCutoff": 65,
    "filterResonance": 38,
    "ampAttack": 100,
    "ampDecay": 42,
    "ampSustain": 82,
    "ampRelease": 57,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 40
  },
  {
    "name": "Drop FX",
    "osc1Wave": 0,
    "osc1Level": 108,
    "filterCutoff": 90,
    "filterResonance": 48,
    "vp1Src": 1,
    "vp1Dst": 0,
    "vp1Int": -55,
    "ampAttack": 0,
    "ampDecay": 45,
    "ampSustain": 0,
    "ampRelease": 28,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 40
  },
  {
    "name": "Wave Rise",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 95,
    "osc2Level": 84,
    "filterCutoff": 28,
    "filterResonance": 72,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 48,
    "lfo1Wave": 2,
    "lfo1Rate": 55,
    "filterEgInt": 52,
    "filterAttack": 72,
    "filterDecay": 100,
    "ampAttack": 5,
    "ampSustain": 100,
    "ampRelease": 47,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 45
  },
  {
    "name": "Alien Vox",
    "osc1Wave": 4,
    "osc1Level": 108,
    "filterCutoff": 68,
    "filterResonance": 88,
    "filterEgInt": 44,
    "filterDecay": 50,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 34,
    "lfo1Wave": 2,
    "lfo1Rate": 75,
    "ampAttack": 5,
    "ampSustain": 92,
    "ampRelease": 54,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 45
  },
  {
    "name": "Ring Planet",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc2Mod": 1,
    "osc1Level": 100,
    "osc2Level": 82,
    "filterCutoff": 66,
    "filterResonance": 72,
    "filterEgInt": 42,
    "filterDecay": 44,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 38,
    "lfo1Wave": 2,
    "lfo1Rate": 75,
    "ampAttack": 3,
    "ampSustain": 92,
    "ampRelease": 52,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 40
  },
  {
    "name": "S&H Alien",
    "osc1Wave": 1,
    "osc1Level": 102,
    "filterCutoff": 75,
    "filterResonance": 68,
    "vp1Src": 2,
    "vp1Dst": 0,
    "vp1Int": 38,
    "lfo1Wave": 3,
    "lfo1Rate": 72,
    "ampAttack": 1,
    "ampDecay": 35,
    "ampSustain": 68,
    "ampRelease": 28,
    "vibratoIntensity": 45,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 40
  },
  {
    "name": "Glitch",
    "osc1Wave": 1,
    "osc2Wave": 1,
    "osc1Level": 100,
    "osc2Level": 82,
    "filterCutoff": 80,
    "filterResonance": 62,
    "vp1Src": 2,
    "vp1Dst": 0,
    "vp1Int": 42,
    "lfo1Wave": 3,
    "lfo1Rate": 88,
    "ampAttack": 0,
    "ampDecay": 30,
    "ampSustain": 58,
    "ampRelease": 22,
    "vibratoIntensity": 43,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 40
  },
  {
    "name": "Metal Hit",
    "osc1Wave": 0,
    "osc2Wave": 0,
    "osc2Mod": 1,
    "osc1Level": 102,
    "osc2Level": 90,
    "filterCutoff": 92,
    "filterResonance": 65,
    "filterEgInt": 40,
    "filterDecay": 22,
    "ampAttack": 0,
    "ampDecay": 30,
    "ampSustain": 0,
    "ampRelease": 22,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 35
  },
  {
    "name": "Alien Talk",
    "osc1Wave": 4,
    "osc2Wave": 1,
    "osc1Level": 100,
    "osc2Level": 58,
    "filterType": 2,
    "filterCutoff": 65,
    "filterResonance": 92,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 42,
    "lfo1Wave": 2,
    "lfo1Rate": 80,
    "ampAttack": 4,
    "ampSustain": 94,
    "ampRelease": 50,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 45
  },
  {
    "name": "Laser FX",
    "osc1Wave": 0,
    "osc1Level": 108,
    "filterCutoff": 100,
    "filterResonance": 52,
    "vp1Src": 1,
    "vp1Dst": 0,
    "vp1Int": 52,
    "ampAttack": 0,
    "ampDecay": 28,
    "ampSustain": 0,
    "ampRelease": 18,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 35
  },
  {
    "name": "Siren",
    "osc1Wave": 0,
    "osc1Level": 108,
    "filterCutoff": 92,
    "filterResonance": 35,
    "vp1Src": 2,
    "vp1Dst": 0,
    "vp1Int": 54,
    "lfo1Wave": 2,
    "lfo1Rate": 70,
    "ampAttack": 5,
    "ampSustain": 100,
    "ampRelease": 35,
    "vibratoIntensity": 40,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 35
  },
  {
    "name": "Drone Low",
    "osc1Wave": 0,
    "osc2Wave": 2,
    "osc1Level": 92,
    "osc2Level": 86,
    "filterCutoff": 45,
    "filterResonance": 30,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 22,
    "lfo1Wave": 2,
    "lfo1Rate": 6,
    "ampAttack": 58,
    "ampSustain": 100,
    "ampRelease": 100,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Drone Mid",
    "osc1Wave": 2,
    "osc2Wave": 0,
    "osc1Level": 88,
    "osc2Level": 86,
    "filterCutoff": 65,
    "filterResonance": 28,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 20,
    "lfo1Wave": 2,
    "lfo1Rate": 8,
    "ampAttack": 50,
    "ampSustain": 100,
    "ampRelease": 100,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Drone High",
    "osc1Wave": 2,
    "osc2Wave": 0,
    "osc1Level": 85,
    "osc2Level": 86,
    "filterCutoff": 75,
    "filterResonance": 25,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 20,
    "lfo1Wave": 2,
    "lfo1Rate": 9,
    "ampAttack": 47,
    "ampSustain": 100,
    "ampRelease": 100,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Wind",
    "osc1Wave": 6,
    "osc1Level": 95,
    "noiseLevel": 82,
    "filterCutoff": 55,
    "filterResonance": 32,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 28,
    "lfo1Wave": 2,
    "lfo1Rate": 12,
    "ampAttack": 42,
    "ampSustain": 100,
    "ampRelease": 100,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 35
  },
  {
    "name": "Rain",
    "osc1Wave": 6,
    "osc1Level": 88,
    "noiseLevel": 88,
    "filterCutoff": 70,
    "filterResonance": 30,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 32,
    "lfo1Wave": 2,
    "lfo1Rate": 30,
    "ampAttack": 22,
    "ampSustain": 100,
    "ampRelease": 82,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 35
  },
  {
    "name": "Static Hiss",
    "osc1Wave": 6,
    "osc1Level": 80,
    "noiseLevel": 95,
    "filterCutoff": 80,
    "filterResonance": 18,
    "ampAttack": 17,
    "ampSustain": 100,
    "ampRelease": 78,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 30
  },
  {
    "name": "Breath",
    "osc1Wave": 3,
    "osc1Level": 72,
    "noiseLevel": 75,
    "filterCutoff": 60,
    "filterResonance": 25,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 24,
    "lfo1Wave": 2,
    "lfo1Rate": 10,
    "ampAttack": 38,
    "ampSustain": 100,
    "ampRelease": 92,
    "vp2Src": 6,
    "vp2Dst": 7,
    "vp2Int": 35
  },
  {
    "name": "Hum",
    "osc1Wave": 2,
    "osc2Wave": 2,
    "osc1Level": 85,
    "osc2Level": 82,
    "filterCutoff": 48,
    "filterResonance": 22,
    "vp1Src": 2,
    "vp1Dst": 4,
    "vp1Int": 16,
    "lfo1Wave": 2,
    "lfo1Rate": 7,
    "ampAttack": 52,
    "ampSustain": 100,
    "ampRelease": 100,
    "vp2Src": 6,
    "vp2Dst": 4,
    "vp2Int": 28
  }
];

module.exports = patches;
